import type { ModuleContent, Question } from "../types.ts";

const mastery = { comprehension: 70, recall: 70, contrast: 70, application: 60 };
const refs = [
  { title: "Kandel et al., Principles of Neural Science", kind: "livro" as const },
  { title: "Sapolsky, Why Zebras Don't Get Ulcers", kind: "livro" as const, note: "estresse como sistema, com ressalvas de divulgação" },
  { title: "LeDoux, Anxious / The Emotional Brain", kind: "livro" as const, note: "ameaça ≠ sentimento de medo" },
];

function q(partial: Question): Question {
  return partial;
}

export const STAGE_2_MODULES: ModuleContent[] = [
  {
    id: "module_09",
    stage: 2,
    number: 9,
    title: "Do circuito ao sistema",
    shortTitle: "Sistemas",
    objective: "Passar do circuito local a sistemas distribuídos sem localizar funções em um único centro.",
    centralQuestion: "Quando muitos circuitos trabalham juntos, o que muda na explicação?",
    prerequisites: ["module_08"],
    estimatedTime: { essential: 8, deepen: 6, questions: 5 },
    concepts: ["distributed_systems", "circuit"],
    introduction:
      "A etapa 1 terminou no circuito. A tentação agora é apontar para uma região e chamá-la de função. Este módulo ensina a subir de escala sem voltar à frenologia.",
    blocks: [
      { id: "m09-q", kind: "question", body: "Se uma lesão em um território altera uma função, a função mora ali?" },
      { id: "m09-a", kind: "answer", body: "Não necessariamente. [[distributed_systems|Sistemas distribuídos]] admitem nós críticos sem exclusividade. Participação ≠ suficiência ≠ localização da experiência." },
      { id: "m09-e", kind: "explain", title: "O que um sistema acrescenta", body: "Um sistema tem dinâmica temporal própria, múltiplos efetores (neural, autonômico, endócrino) e dependência de contexto. Não é um circuito maior desenhado com a mesma caneta." },
      { id: "m09-r", kind: "recall", body: "Dê um exemplo em que remover uma peça muda a música sem que a peça seja a música." },
      { id: "m09-l", kind: "limit", title: "Neuroimagem", body: "Um mapa BOLD é consistente com participação em uma tarefa. Não é a fotografia de uma faculdade mental.", layer: 2 },
    ],
    misconceptions: [{ claim: "Cada função tem um centro.", whyPlausible: "Nomes de áreas e cores de exames.", problem: "Erro de exclusividade.", better: "Redes com especialização relativa." }],
    integration: "O próximo módulo aplica isso à emoção — o exemplo mais maltratado pela divulgação.",
    relatedModules: ["module_01", "module_10", "module_16"],
    questions: [
      q({ id: "m09-q1", moduleId: "module_09", conceptIds: ["distributed_systems"], type: "misconception", difficulty: 1, prompt: "Qual formulação é melhor?", options: [{ id: "a", text: "A função X mora na área Y." }, { id: "b", text: "A área Y participa de redes envolvidas em X; isso não esgota X." }], correctAnswer: "b", explanation: "Participação sem exclusividade.", hint1: "Módulo 1, de novo.", hint2: "Suficiência.", hint3: "Redes.", errorKind: "scale" }),
      q({ id: "m09-q2", moduleId: "module_09", conceptIds: ["distributed_systems"], type: "limit", difficulty: 2, prompt: "Uma região 'acende' em um exame durante medo relatado. Podemos concluir que a região é o medo?", options: [{ id: "a", text: "Sim, ativação prova identidade." }, { id: "b", text: "Não. Ativação é correlata, lenta e ambígua; medo é um processo com vários componentes." }], correctAnswer: "b", explanation: "Correlação hemodinâmica ≠ identidade do fenômeno.", hint1: "O que o sinal BOLD mede?", hint2: "Proxy, não o sentimento.", hint3: "Não identifique.", errorKind: "causal" }),
      q({ id: "m09-q3", moduleId: "module_09", conceptIds: ["circuit"], type: "recall", difficulty: 1, prompt: "O que um sistema tem que um único circuito local pode não ter?", correctAnswer: "open", modelAnswer: "Múltiplos territórios, efetores de temporalidades distintas (neural rápido, endócrino lento) e dependência de contexto corporal e social.", explanation: "Escala e tempo.", hint1: "Tempo e efetores.", hint2: "Hormônio versus sinapse.", hint3: "Distribuição." }),
      q({ id: "m09-q4", moduleId: "module_09", conceptIds: ["distributed_systems"], type: "application", difficulty: 2, prompt: "Um título de divulgação diz: 'cientistas encontram a área da criatividade'. Qual pergunta você faz primeiro?", options: [{ id: "a", text: "Qual tarefa, qual medida, qual rede, o que não se pode concluir?" }, { id: "b", text: "Como compro o curso para ativar essa área?" }], correctAnswer: "a", explanation: "Hábito científico contra o título.", hint1: "Tarefa e medida.", hint2: "Rede, não área.", hint3: "Limite.", errorKind: "generalization" }),
      q({ id: "m09-q5", moduleId: "module_09", conceptIds: ["circuit", "distributed_systems"], type: "counterfactual", difficulty: 2, prompt: "Se um nó considerado 'crítico' fosse removido e a função apenas se degradasse (sem sumir), a interpretação mais coerente seria:", options: [{ id: "a", text: "O nó era supérfluo, então a função nunca dependeu dele." }, { id: "b", text: "O nó participa da rede — necessidade e suficiência não se confundem; a rede compensa parcialmente." }], correctAnswer: "b", explanation: "Necessidade parcial + compensação distribuída.", hint1: "Participação.", hint2: "Compensação.", hint3: "Não sinônimo de essência.", errorKind: "causal" }),
    ],
    summary: { shouldKnow: ["Definir sistema distribuído.", "Ler lesão e imagem com cautela causal."], acquiredConcepts: ["distributed_systems"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_10",
    stage: 2,
    number: 10,
    title: "Emoção não é uma área",
    shortTitle: "Emoção",
    objective: "Tratar emoção como processo distribuído: avaliação, corpo, ação, sentimento, aprendizagem.",
    centralQuestion: "Se emoção não mora em um lugar, como descrevê-la sem esvaziá-la?",
    prerequisites: ["module_09"],
    estimatedTime: { essential: 8, deepen: 6, questions: 5 },
    concepts: ["emotion_as_process"],
    introduction: "A divulgação ama centros emocionais. A trilha recusa. Emoção atravessa níveis: do autonômico ao significado social.",
    blocks: [
      { id: "m10-q", kind: "question", body: "O que está acontecendo em um episódio chamado 'medo' — e em quais níveis?" },
      { id: "m10-a", kind: "answer", body: "Pode haver avaliação de relevância, alterações corporais, tendência de ação, sentimento e aprendizagem. [[emotion_as_process|Emoção como processo]] não é um módulo que se liga." },
      { id: "m10-m", kind: "mechanism", title: "Componentes possíveis (não obrigatórios todos)", steps: [
        { id: "v", title: "Avaliação", body: "O que isso prediz para o organismo?" },
        { id: "b", title: "Corpo", body: "Autonômico, endócrino, interocepção." },
        { id: "a", title: "Ação", body: "Preparar, evitar, aproximar, congelar — tendências, não destino." },
        { id: "s", title: "Sentimento", body: "A experiência relatável, que não se reduz ao circuito." },
        { id: "l", title: "Aprendizagem", body: "O episódio atualiza previsões." },
      ]},
      { id: "m10-r", kind: "recall", body: "Liste três componentes de um episódio afetivo sem usar o nome de uma área." },
      { id: "m10-c", kind: "limit", title: "Não há uma teoria única", body: "Há debates (construcionismo, teorias de emoções básicas, avaliação). O app não escolhe um vencedor: escolhe não localizar o fenômeno em um núcleo.", layer: 2 },
    ],
    misconceptions: [{ claim: "Emoção é o sistema límbico.", whyPlausible: "O rótulo 'límbico' pegou.", problem: "O conjunto 'límbico' é historicamente instável e não é um órgão da emoção.", better: "Processos afetivos recrutam redes amplas, incluindo córtex, tronco e corpo." }],
    integration: "Agora podemos falar da amígdala com o vocabulário certo: participação, não identidade.",
    relatedModules: ["module_11", "module_15", "module_26"],
    questions: [
      q({ id: "m10-q1", moduleId: "module_10", conceptIds: ["emotion_as_process"], type: "misconception", difficulty: 1, prompt: "Emoção é melhor descrita como:", options: [{ id: "a", text: "Uma área que se liga." }, { id: "b", text: "Um processo com componentes avaliativos, corporais, de ação e, por vezes, de sentimento e aprendizagem." }], correctAnswer: "b", explanation: "Processo, não lugar.", hint1: "Vários componentes.", hint2: "Corpo incluso.", hint3: "Não uma área.", errorKind: "scale" }),
      q({ id: "m10-q2", moduleId: "module_10", conceptIds: ["emotion_as_process"], type: "application", difficulty: 2, prompt: "Alguém treme antes de falar em público. Qual análise é mais precisa?", options: [{ id: "a", text: "A área do medo ligou." }, { id: "b", text: "Há avaliação de ameaça social, ajustes corporais e, possivelmente, aprendizagem de episódios anteriores — sem que isso diagnostique um transtorno." }], correctAnswer: "b", explanation: "Níveis + limite clínico.", hint1: "Não nomeie uma área como causa.", hint2: "Inclua o social.", hint3: "Não diagnostique.", errorKind: "scale" }),
      q({ id: "m10-q3", moduleId: "module_10", conceptIds: ["emotion_as_process"], type: "recall", difficulty: 1, prompt: "Por que 'emoção não é uma área' não significa 'emoção não é biológica'?", correctAnswer: "open", modelAnswer: "Porque processos distribuídos ainda são biológicos. Distribuído ≠ imaterial. O erro é a localização exclusiva, não a biologia.", explanation: "Anti-dualismo e anti-frenologia ao mesmo tempo.", hint1: "Distribuído ainda é corpo.", hint2: "Várias redes.", hint3: "Não é alma versus cérebro." }),
      q({ id: "m10-q4", moduleId: "module_10", conceptIds: ["levels_of_analysis"], type: "limit", difficulty: 2, prompt: "Uma alteração autonômica prova o conteúdo da experiência relatada?", options: [{ id: "a", text: "Sim, taquicardia é medo." }, { id: "b", text: "Não. O mesmo ajuste corporal entra em vários episódios; o conteúdo exige contexto e, quando houver, relato." }], correctAnswer: "b", explanation: "Fisiologia não é um dicionário de sentimentos.", hint1: "Correr também acelera o coração.", hint2: "Ambiguidade.", hint3: "Contexto.", errorKind: "causal" }),
      q({ id: "m10-q5", moduleId: "module_10", conceptIds: ["emotion_as_process"], type: "counterfactual", difficulty: 2, prompt: "Se um episódio afetivo perdesse o componente de aprendizagem, o que aconteceria com os episódios seguintes?", options: [{ id: "a", text: "Nada: cada episódio é isolado por natureza." }, { id: "b", text: "As predições não seriam atualizadas; padrões de resposta tenderiam a se repetir mesmo em contextos onde não cabem mais." }], correctAnswer: "b", explanation: "Componente de aprendizagem é integrante, não decorativo.", hint1: "Predição.", hint2: "Contexto muda.", hint3: "Rigidez.", errorKind: "causal" }),
    ],
    summary: { shouldKnow: ["Listar componentes de um episódio afetivo.", "Recusar o centro emocional."], acquiredConcepts: ["emotion_as_process"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_11",
    stage: 2,
    number: 11,
    title: "Amígdala",
    shortTitle: "Amígdala",
    objective: "Situar a amígdala em circuitos de relevância e aprendizagem, sem transformá-la no medo.",
    centralQuestion: "O que a amígdala faz — e o que não podemos concluir daí?",
    prerequisites: ["module_10"],
    estimatedTime: { essential: 8, deepen: 6, questions: 5 },
    concepts: ["amygdala"],
    introduction: "Depois de recusar o centro da emoção, podemos estudar um nó famoso com precisão. A amígdala é um conjunto de núcleos, não um botão.",
    blocks: [
      { id: "m11-q", kind: "question", body: "Se a amígdala participa de respostas a ameaça, ela 'é' o medo?" },
      { id: "m11-a", kind: "answer", body: "Não. A [[amygdala|amígdala]] participa de circuitos envolvidos na aprendizagem e no processamento de estímulos biologicamente relevantes. Em determinadas situações, sua atividade contribui para respostas associadas à ameaça." },
      { id: "m11-e", kind: "explain", title: "O que a evidência mostra", body: "Lesões alteram certos aprendizados de ameaça e a atribuição de relevância. Isso é participação. Pessoas com lesão ainda têm vida afetiva. Núcleos diferentes fazem coisas diferentes." },
      { id: "m11-r", kind: "recall", body: "Reescreva 'a amígdala é o medo' na formulação do manuscrito." },
      { id: "m11-d", kind: "explain", title: "Detalhe de núcleos", body: "Lateral, basal, central: portas de entrada, integração e saídas para hipotálamo e tronco, em linhas gerais. Útil no aprofundamento; não necessário para o modelo essencial.", layer: 2 },
    ],
    misconceptions: [{ claim: "A amígdala é responsável pelo medo.", whyPlausible: "Resumo escolar e títulos.", problem: "Função única para estrutura complexa; confunde detecção de relevância, aprendizagem e experiência.", better: "Participa de circuitos de relevância e aprendizagem; o medo como experiência é mais amplo." }],
    integration: "Saídas da amígdala conversam com hipotálamo — próximo módulo — sem que isso funda as duas estruturas em 'o emocional'.",
    relatedModules: ["module_10", "module_12", "module_15", "module_26"],
    questions: [
      q({ id: "m11-q1", moduleId: "module_11", conceptIds: ["amygdala"], type: "misconception", difficulty: 1, prompt: "Qual formulação é mais adequada?", options: [{ id: "a", text: "A amígdala é responsável pelo medo." }, { id: "b", text: "A amígdala participa de circuitos envolvidos na aprendizagem e no processamento de estímulos biologicamente relevantes." }], correctAnswer: "b", explanation: "A frase-guia do projeto.", hint1: "Participe, não seja.", hint2: "Relevância, não só medo.", hint3: "A opção longa é a precisa.", errorKind: "language" }),
      q({ id: "m11-q2", moduleId: "module_11", conceptIds: ["amygdala"], type: "limit", difficulty: 2, prompt: "Ativação da amígdala em fMRI durante uma foto prova que a pessoa sentiu medo?", options: [{ id: "a", text: "Sim." }, { id: "b", text: "Não. O sinal não identifica o conteúdo subjetivo nem a suficiência da estrutura." }], correctAnswer: "b", explanation: "Mesmo nó, mesma cautela da imagem.", hint1: "Saliência também recruta.", hint2: "Proxy.", hint3: "Não prova o sentimento.", errorKind: "causal" }),
      q({ id: "m11-q3", moduleId: "module_11", conceptIds: ["amygdala"], type: "recall", difficulty: 1, prompt: "O que uma lesão amigdaliana permite e o que não permite concluir?", correctAnswer: "open", modelAnswer: "Permite concluir que certos aprendizados e respostas dependem da integridade da estrutura. Não permite concluir que toda emoção ou todo medo 'são' a amígdala.", explanation: "Participação versus identidade.", hint1: "O que some versus o que resta.", hint2: "Aprendizado de ameaça.", hint3: "Não a vida afetiva inteira." }),
      q({ id: "m11-q4", moduleId: "module_11", conceptIds: ["amygdala"], type: "application", difficulty: 2, prompt: "Um texto de autoajuda diz: 'desligue sua amígdala para negociar melhor'. O problema é:", options: [{ id: "a", text: "A amígdala não existe." }, { id: "b", text: "Trata uma estrutura como interruptor de desempenho e ignora contexto, avaliação e limites da intervenção." }], correctAnswer: "b", explanation: "Prévia da etapa 4: não transformar anatomia em botão.", hint1: "Interruptor.", hint2: "Não se desliga como um app.", hint3: "Contexto.", errorKind: "generalization" }),
      q({ id: "m11-q5", moduleId: "module_11", conceptIds: ["amygdala"], type: "counterfactual", difficulty: 2, prompt: "Se um estudo lesionasse seletivamente o núcleo lateral em animais, a previsão mais coerente seria:", options: [{ id: "a", text: "Perda total de qualquer resposta emocional." }, { id: "b", text: "Prejuízo específico em certos aprendizados de ameaça, com preservação de outras respostas — porque núcleos diferentes fazem coisas diferentes." }], correctAnswer: "b", explanation: "Especificidade de núcleos, não apagão emocional.", hint1: "Núcleos diferentes.", hint2: "Aprendizado específico.", hint3: "Sem apagão.", errorKind: "scale" }),
    ],
    summary: { shouldKnow: ["Usar a formulação de participação.", "Separar aprendizagem de ameaça e sentimento de medo."], acquiredConcepts: ["amygdala"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_12",
    stage: 2,
    number: 12,
    title: "Hipotálamo",
    shortTitle: "Hipotálamo",
    objective: "Ver o hipotálamo como coordenador de homeostase e saídas autonômico-endócrinas, não como centro dos instintos.",
    centralQuestion: "Como o estado interno do corpo entra na história neural?",
    prerequisites: ["module_09"],
    estimatedTime: { essential: 7, deepen: 5, questions: 4 },
    concepts: ["hypothalamus"],
    introduction: "Circuitos de avaliação precisam de um corpo que tenha temperatura, glicose, água, defesa. O hipotálamo é um dos grandes acopladores.",
    blocks: [
      { id: "m12-q", kind: "question", body: "Por que um 'mapa só de córtex' não explica fome, febre ou defesa?" },
      { id: "m12-a", kind: "answer", body: "Porque o [[hypothalamus|hipotálamo]] coordena funções homeostáticas e endócrinas: liga estado interno a padrões autonômicos e hormonais." },
      { id: "m12-e", kind: "explain", title: "Núcleos, não um botão", body: "Há especialização (térmico, hídrico, energético, defensivo, reprodutivo, entre outros). Chamar tudo de 'instinto' apaga essa partição e a regulação contextual." },
      { id: "m12-r", kind: "recall", body: "Em uma frase: o hipotálamo acopla o quê a quê?" },
      { id: "m12-l", kind: "connection", title: "Ponte para o HPA", body: "Certos núcleos hipotalâmicos iniciam a cascata que o módulo 13 chama de eixo HPA. Já separe: hipotálamo ≠ cortisol ≠ 'estresse'." },
    ],
    misconceptions: [{ claim: "O hipotálamo é o botão dos instintos.", whyPlausible: "Estimulação em animais produz padrões dramáticos.", problem: "Padrões de estimulação não são a ontologia da vida motivada humana.", better: "Coordenador de homeostase e de saídas fisiológicas, em diálogo com córtex, amígdala, tronco e órgãos." }],
    integration: "O eixo HPA é um efetor lento dessa coordenação.",
    relatedModules: ["module_11", "module_13"],
    questions: [
      q({ id: "m12-q1", moduleId: "module_12", conceptIds: ["hypothalamus"], type: "recognition", difficulty: 1, prompt: "O hipotálamo é melhor descrito como:", options: [{ id: "a", text: "O centro único da emoção." }, { id: "b", text: "Conjunto de núcleos que coordena homeostase e saídas autonômico-endócrinas." }], correctAnswer: "b", explanation: "Acoplador, não essência afetiva.", hint1: "Corpo interno.", hint2: "Hormônio e autonômico.", hint3: "Núcleos." }),
      q({ id: "m12-q2", moduleId: "module_12", conceptIds: ["hypothalamus"], type: "counterfactual", difficulty: 2, prompt: "Se o hipotálamo não pudesse acionar saídas endócrinas, o que seria afetado mais diretamente?", options: [{ id: "a", text: "A condução saltatória nos nódulos de Ranvier." }, { id: "b", text: "A coordenação lenta de eixos como o HPA." }], correctAnswer: "b", explanation: "Efetor lento versus condução axônica (outro nível).", hint1: "Hormônio.", hint2: "Tempo de minutos a horas.", hint3: "HPA.", errorKind: "causal" }),
      q({ id: "m12-q3", moduleId: "module_12", conceptIds: ["hypothalamus"], type: "recall", difficulty: 1, prompt: "Por que não reduzir o hipotálamo a 'instinto'?", correctAnswer: "open", modelAnswer: "Porque ele particiona funções homeostáticas e trabalha em rede; 'instinto' é um rótulo que apaga mecanismo, contexto e diversidade de núcleos.", explanation: "Rótulo versus mecanismo.", hint1: "Vários núcleos.", hint2: "Homeostase.", hint3: "Contexto." }),
      q({ id: "m12-q4", moduleId: "module_12", conceptIds: ["hypothalamus"], type: "application", difficulty: 2, prompt: "Febre, sede e um susto compartilham o hipotálamo. Isso prova que são a mesma emoção?", options: [{ id: "a", text: "Sim, tudo é o mesmo centro." }, { id: "b", text: "Não. Compartilhar um coordenador fisiológico não identitifica os fenômenos." }], correctAnswer: "b", explanation: "Mesma moral: participação ≠ identidade.", hint1: "Um aeroporto não é todas as viagens.", hint2: "Núcleos distintos.", hint3: "Não identifique.", errorKind: "generalization" }),
      q({ id: "m12-q5", moduleId: "module_12", conceptIds: ["hypothalamus"], type: "limit", difficulty: 2, prompt: "Estimulação elétrica em um núcleo hipotalâmico produz um padrão dramático em animal. Que conclusão sobre humanos essa observação NÃO permite?", options: [{ id: "a", text: "Que a ontologia da vida motivada humana se reduz àquele padrão." }, { id: "b", text: "Que aquele núcleo participa da coordenação de tal função." }], correctAnswer: "a", explanation: "Estimulação mostra participação, não semântica da experiência humana.", hint1: "Ontologia.", hint2: "Não sinônimo.", hint3: "Participação, sim; identidade, não.", errorKind: "scale" }),
    ],
    summary: { shouldKnow: ["Acoplar estado interno a saídas.", "Preparar o eixo HPA sem personificá-lo."], acquiredConcepts: ["hypothalamus"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_13",
    stage: 2,
    number: 13,
    title: "Estresse e eixo HPA",
    shortTitle: "Eixo HPA",
    objective: "Descrever a cascata HPA e o cortisol sem personificá-los como 'o estresse'.",
    centralQuestion: "O que a resposta a um desafio faz no tempo lento — e o que isso não prova?",
    prerequisites: ["module_12"],
    estimatedTime: { essential: 9, deepen: 6, questions: 5 },
    concepts: ["hpa_axis", "cortisol", "stress_response", "allostasis"],
    introduction: "Estresse virou palavra-coringa. Aqui separamos resposta aguda, eixo HPA, cortisol cotidiano e modelos de alostase.",
    blocks: [
      { id: "m13-q", kind: "question", body: "Todo desafio 'é' cortisol?" },
      { id: "m13-a", kind: "answer", body: "Não. A [[stress_response|resposta a desafios]] inclui simpático (rápido) e [[hpa_axis|eixo HPA]] (mais lento). O [[cortisol|cortisol]] tem ritmo diário e ações metabólicas mesmo fora do drama." },
      { id: "m13-d", kind: "diagram", diagram: "hpa", title: "Cascata", body: "Hipotálamo (CRH) → hipófise (ACTH) → adrenal (glicocorticoides) → feedback." },
      { id: "m13-m", kind: "mechanism", title: "Tempos diferentes", steps: [
        { id: "s", title: "Segundos", body: "Autonômico: frequência cardíaca, pupilas, broncodilatação possível." },
        { id: "m", title: "Minutos–horas", body: "HPA e mobilização energética." },
        { id: "c", title: "Crônico", body: "Não é só 'agudo repetido'. Há adaptação, custo, contexto. [[allostasis|Alostase]] é um modelo, não um órgão." },
      ]},
      { id: "m13-r", kind: "recall", body: "Cite uma função do cortisol que não é 'fazer a pessoa estressada'." },
      { id: "m13-h", kind: "limit", title: "Saúde", body: "Conhecimento do eixo não diagnostica seu cansaço nem substitui avaliação clínica. Cuidado com kits de 'nível de cortisol' como veredito de caráter.", layer: 1 },
    ],
    misconceptions: [{ claim: "Cortisol é o hormônio do estresse.", whyPlausible: "Sobe em muitos desafios.", problem: "Personificação; ignora ritmo circadiano e funções permissivas.", better: "Glicocorticoide com ações amplas; o HPA é um efetor, não o sinônimo de estresse." }],
    integration: "Da defesa passamos à valorização e à aprendizagem: dopamina, sem o mito do prazer.",
    relatedModules: ["module_12", "module_14", "module_26"],
    questions: [
      q({ id: "m13-q1", moduleId: "module_13", conceptIds: ["cortisol"], type: "misconception", difficulty: 1, prompt: "Qual formulação é melhor?", options: [{ id: "a", text: "Cortisol é o hormônio do estresse." }, { id: "b", text: "Cortisol é um glicocorticoide com ações cotidianas que também participa de respostas a desafios." }], correctAnswer: "b", explanation: "Anti-personificação.", hint1: "Ritmo circadiano.", hint2: "Metabolismo.", hint3: "Participa, não é.", errorKind: "language" }),
      q({ id: "m13-q2", moduleId: "module_13", conceptIds: ["hpa_axis"], type: "relation", difficulty: 1, prompt: "A ordem típica do eixo HPA é:", options: [{ id: "a", text: "Adrenal → córtex visual → amígdala." }, { id: "b", text: "Hipotálamo → hipófise → adrenal." }], correctAnswer: "b", explanation: "A sigla é o mapa.", hint1: "H-P-A.", hint2: "Hormônios em cascata.", hint3: "CRH/ACTH/cortisol em linhas gerais." }),
      q({ id: "m13-q3", moduleId: "module_13", conceptIds: ["stress_response"], type: "counterfactual", difficulty: 2, prompt: "Se apenas o eixo HPA fosse bloqueado, a resposta a um susto imediato:", options: [{ id: "a", text: "Desapareceria por completo, porque estresse é só cortisol." }, { id: "b", text: "Manteria componentes autonômicos rápidos; a coordenação endócrina lenta estaria comprometida." }], correctAnswer: "b", explanation: "Múltiplos efetores, múltiplos tempos.", hint1: "Simpático ainda existe.", hint2: "Segundos versus minutos.", hint3: "Não é um único modo.", errorKind: "causal" }),
      q({ id: "m13-q4", moduleId: "module_13", conceptIds: ["allostasis"], type: "application", difficulty: 2, prompt: "Usar 'alostase' como sinônimo de 'estresse ruim' é um erro porque:", options: [{ id: "a", text: "Alostase é um modelo de ajuste antecipatório, não um veredito moral." }, { id: "b", text: "Alostase é um osso do crânio." }], correctAnswer: "a", explanation: "Modelo versus insulto.", hint1: "Antecipação.", hint2: "Custo pode existir, mas não é o nome.", hint3: "Não moralize.", errorKind: "language" }),
      q({ id: "m13-q5", moduleId: "module_13", conceptIds: ["cortisol", "hpa_axis"], type: "recall", difficulty: 2, prompt: "Por que dizer 'meu cortisol está alto' como veredito de vida é problemático?", correctAnswer: "open", modelAnswer: "Porque o cortisol tem ritmo circadiano, funções permissivas cotidianas e varia com sono, alimentação, hora do dia e método de medida; um valor não é um diagnóstico de caráter nem de patologia.", explanation: "Anti-personificação em contexto pop.", hint1: "Ritmo diário.", hint2: "Contexto de medida.", hint3: "Não veredito." }),
    ],
    summary: { shouldKnow: ["Desenhar HPA.", "Separar simpático e endócrino.", "Falar de cortisol sem vilania."], acquiredConcepts: ["hpa_axis", "cortisol", "stress_response", "allostasis"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_14",
    stage: 2,
    number: 14,
    title: "Recompensa e dopamina",
    shortTitle: "Dopamina",
    objective: "Substituir 'molécula do prazer' por circuito, receptor, contexto e erro de predição.",
    centralQuestion: "Se não é prazer, o que a dopamina ajuda a fazer?",
    prerequisites: ["module_07", "module_09"],
    estimatedTime: { essential: 9, deepen: 7, questions: 6 },
    concepts: ["dopamine", "reward_prediction_error", "ventral_striatum"],
    introduction: "Poucas moléculas foram tão maltratadas. Este módulo usa tudo que você já sabe: receptor, circuito, nível de análise.",
    blocks: [
      { id: "m14-q", kind: "question", body: "A dopamina é responsável pelo prazer?" },
      { id: "m14-a", kind: "answer", body: "Não como modelo final. A [[dopamine|dopamina]] participa de diferentes processos; o efeito depende do circuito, do receptor e do contexto. Em certos paradigmas, o sinal acompanha [[reward_prediction_error|erro de predição de recompensa]]." },
      { id: "m14-c", kind: "explain", title: "Três vias, no essencial", body: "Nigroestriatal (movimento), mesolímbica (valorização/aprendizagem), mesocortical (funções executivas, entre outras). Uma molécula, operações distintas. O [[ventral_striatum|estriado ventral]] é um nó — não o centro do prazer." },
      { id: "m14-rpe", kind: "mechanism", title: "Erro de predição, em três linhas", steps: [
        { id: "e", title: "Esperado", body: "O sistema prediz." },
        { id: "o", title: "Obtido", body: "O mundo entrega ou não." },
        { id: "d", title: "Diferença", body: "O sinal pode subir com surpresa melhor que o previsto e cair com decepção. Isso ensina, não 'é' o gosto." },
      ]},
      { id: "m14-r", kind: "recall", body: "Reescreva 'dopamina = prazer' em uma frase que sobreviveria a uma revisão por pares." },
      { id: "m14-l", kind: "limit", title: "Pesquisa ativa", body: "Há debate sobre saliência, invigoração, esforço e prazer. O app ensina a recusar o slogan; não fecha a literatura.", layer: 2 },
    ],
    misconceptions: [{ claim: "A dopamina é a molécula do prazer.", whyPlausible: "Drogas, títulos, metáforas de 'disparo de recompensa'.", problem: "Prazer, wanting, aprendizagem e movimento se separam experimentalmente em vários desenhos.", better: "Neuromodulador de vários circuitos; em alguns, sinal de erro de predição." }],
    integration: "Relaciona-se com receptores (7), memória (15), decisão (20) e hábitos (22).",
    relatedModules: ["module_07", "module_15", "module_20", "module_22"],
    questions: [
      q({ id: "m14-q1", moduleId: "module_14", conceptIds: ["dopamine"], type: "misconception", difficulty: 1, prompt: "Qual afirmação descreve melhor a dopamina?", options: [{ id: "a", text: "É a molécula responsável pelo prazer." }, { id: "b", text: "Participa de diferentes processos; o efeito depende de circuito, receptor e contexto." }, { id: "c", text: "Só participa da motivação." }], correctAnswer: "b", explanation: "Os distratores são os erros reais do manuscrito.", hint1: "Anti-personagem.", hint2: "Movimento também.", hint3: "Circuito e receptor.", errorKind: "generalization" }),
      q({ id: "m14-q2", moduleId: "module_14", conceptIds: ["reward_prediction_error"], type: "recognition", difficulty: 2, prompt: "Erro de predição de recompensa é:", options: [{ id: "a", text: "A prova de que a pessoa sentiu prazer." }, { id: "b", text: "Uma diferença entre obtido e esperado, observada em certos padrões dopaminérgicos, útil para aprendizagem." }], correctAnswer: "b", explanation: "Sinal de aprendizagem, não dicionário de sentimento.", hint1: "Esperado versus obtido.", hint2: "Surpresa.", hint3: "Não é o gosto.", errorKind: "causal" }),
      q({ id: "m14-q3", moduleId: "module_14", conceptIds: ["dopamine"], type: "counterfactual", difficulty: 2, prompt: "Se a dopamina fosse apenas 'prazer', a via nigroestriatal e o Parkinson seriam…", options: [{ id: "a", text: "Irrelevantes para o modelo, o que mostra que o slogan é estreito demais." }, { id: "b", text: "A prova de que prazer mora no movimento." }], correctAnswer: "a", explanation: "A diversidade de vias mata o personagem único.", hint1: "Movimento.", hint2: "Mais de uma via.", hint3: "Slogan estreito.", errorKind: "generalization" }),
      q({ id: "m14-q4", moduleId: "module_14", conceptIds: ["ventral_striatum"], type: "application", difficulty: 2, prompt: "Um anúncio diz que um produto 'libera dopamina no accumbens, portanto vicia'. O problema principal:", options: [{ id: "a", text: "O accumbens não existe." }, { id: "b", text: "Liberações e nós de circuito não equivalem a um veredito de vício nem ao prazer como essência." }], correctAnswer: "b", explanation: "Salto de nível + marketing.", hint1: "Mecanismo local ≠ diagnóstico.", hint2: "Não personifique.", hint3: "Vício é fenômeno complexo.", errorKind: "scale" }),
      q({ id: "m14-q5", moduleId: "module_14", conceptIds: ["dopamine"], type: "recall", difficulty: 2, prompt: "Explique, com suas palavras, por que 'dopamina é prazer' falha.", correctAnswer: "open", modelAnswer: "Porque a molécula opera em circuitos de movimento, aprendizagem e esforço, via receptores distintos; padrões associados a predição não se identificam com o sentimento de prazer.", explanation: "Se a resposta só disser 'é mais complicado', peça o mecanismo.", hint1: "Vias.", hint2: "Predição.", hint3: "Receptor." }),
    ],
    summary: { shouldKnow: ["Recusar o slogan.", "Citar pelo menos duas vias.", "Definir erro de predição sem ontologizá-lo."], acquiredConcepts: ["dopamine", "reward_prediction_error", "ventral_striatum"] },
    masteryCriteria: mastery,
    references: [
      { title: "Schultz, dopaminergic reward prediction error", kind: "revisao" },
      { title: "Berridge, wanting vs liking", kind: "revisao" },
    ],
    contentVersion: "1.0",
  },
  {
    id: "module_15",
    stage: 2,
    number: 15,
    title: "Memória e emoção",
    shortTitle: "Memória e emoção",
    objective: "Explicar a modulação afetiva da memória sem transformar vivacidade em verdade.",
    centralQuestion: "Por que alguns episódios grudam — e por que isso não os torna infalíveis?",
    prerequisites: ["module_11", "module_14"],
    estimatedTime: { essential: 8, deepen: 5, questions: 4 },
    concepts: ["memory_emotion"],
    introduction: "Amígdala, arousal e glicocorticoides podem modular consolidação. A memória continua reconstrutiva. Este módulo impede o mito da gravação em HD.",
    blocks: [
      { id: "m15-q", kind: "question", body: "Um episódio intenso é uma fita intacta?" },
      { id: "m15-a", kind: "answer", body: "Não. A [[memory_emotion|modulação emocional]] pode favorecer encoding e consolidação de alguns aspectos. Recuperação ainda reconstrói. Vivacidade ≠ acurácia." },
      { id: "m15-e", kind: "explain", title: "O que pode estar acontecendo", body: "Arousal, noradrenalina, glicocorticoides em janelas de dose e tempo, e circuitos que incluem amígdala e hipocampo, em linhas gerais, modulam a probabilidade de persistência. 'Em linhas gerais' importa: não é uma lei do tipo sempre-grava." },
      { id: "m15-r", kind: "recall", body: "Separe em duas colunas: o que a emoção pode fazer pela memória, e o que ela não garante." },
      { id: "m15-l", kind: "limit", title: "Relatos e trauma", body: "Este app não trata, diagnostica nem interpreta trauma clínico. A lição é epistêmica: intensidade subjetiva não é prova forense.", layer: 1 },
    ],
    misconceptions: [{ claim: "Memória emocional é fotográfica.", whyPlausible: "Detalhes vívidos convencem.", problem: "Confunde confiança e riqueza fenomênica com fidelidade.", better: "Modulação de persistência + reconstrução falível." }],
    integration: "A etapa 3 vai separar sistemas de memória com mais granularidade. Aqui o ponto é a ponte afetiva.",
    relatedModules: ["module_11", "module_13", "module_18"],
    questions: [
      q({ id: "m15-q1", moduleId: "module_15", conceptIds: ["memory_emotion"], type: "misconception", difficulty: 1, prompt: "Qual é mais adequada?", options: [{ id: "a", text: "Eventos emocionais gravam um vídeo infalível." }, { id: "b", text: "Estados afetivos podem modular encoding e consolidação; a lembrança permanece reconstrutiva." }], correctAnswer: "b", explanation: "Vivacidade ≠ verdade.", hint1: "Reconstrução.", hint2: "Modula, não sela.", hint3: "Falível.", errorKind: "generalization" }),
      q({ id: "m15-q2", moduleId: "module_15", conceptIds: ["memory_emotion"], type: "limit", difficulty: 2, prompt: "Alta confiança em uma lembrança intensa autoriza tratá-la como registro literal?", options: [{ id: "a", text: "Sim, confiança é acurácia." }, { id: "b", text: "Não. Confiança e acurácia se separam com frequência." }], correctAnswer: "b", explanation: "Pergunta de limite.", hint1: "Testemunho.", hint2: "Dissociação.", hint3: "Não identifique.", errorKind: "causal" }),
      q({ id: "m15-q3", moduleId: "module_15", conceptIds: ["memory_emotion"], type: "recall", difficulty: 1, prompt: "Como a amígdala entra nesta história sem voltar a ser 'o medo'?", correctAnswer: "open", modelAnswer: "Como participante de circuitos que modulam a consolidação de material relevante, não como gravador da experiência nem como essência do afeto.", explanation: "Participação outra vez.", hint1: "Modulação.", hint2: "Relevância.", hint3: "Não identidade." }),
      q({ id: "m15-q4", moduleId: "module_15", conceptIds: ["memory_emotion"], type: "application", difficulty: 2, prompt: "Um estudante só estuda quando está em pânico, porque 'emociona e grava'. O risco conceitual:", options: [{ id: "a", text: "Confundir arousal com método infalível e ignorar custo, foco estreito e reconstrução." }, { id: "b", text: "Nenhum: pânico é a técnica ideal." }], correctAnswer: "a", explanation: "Aplicação pedagógica honesta.", hint1: "Custo.", hint2: "Atenção estreita.", hint3: "Não é HD.", errorKind: "generalization" }),
      q({ id: "m15-q5", moduleId: "module_15", conceptIds: ["memory_emotion", "amygdala"], type: "counterfactual", difficulty: 2, prompt: "Se a modulação afetiva estivesse ausente durante um evento importante, o que aconteceria com a memória posterior?", options: [{ id: "a", text: "Ficaria idêntica: modulação afetiva é decorativa." }, { id: "b", text: "A probabilidade de persistência de certos aspectos tenderia a cair, mas a reconstrução na recuperação continuaria como sempre." }], correctAnswer: "b", explanation: "Modulação de persistência ≠ ausência de reconstrução.", hint1: "Persistência.", hint2: "Reconstrução permanece.", hint3: "Modula, não cria a fita.", errorKind: "causal" }),
    ],
    summary: { shouldKnow: ["Separar vivacidade e acurácia.", "Falar de modulação, não de fita."], acquiredConcepts: ["memory_emotion"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_16",
    stage: 2,
    number: 16,
    title: "Integração sistêmica",
    shortTitle: "Integração 2",
    objective: "Fechar a etapa 2 com a cadeia informação → circuitos → avaliação → corpo → aprendizagem → comportamento, sem reduzir emoção a uma região.",
    centralQuestion: "Como as peças sistêmicas se encaixam sem virar um único órgão da alma?",
    prerequisites: ["module_13", "module_14", "module_15"],
    estimatedTime: { essential: 7, deepen: 5, questions: 4 },
    concepts: ["distributed_systems", "emotion_as_process"],
    introduction: "Não há conceito novo obrigatório. Há um mapa: o que você deve conseguir contar a alguém sem usar 'centro de'.",
    blocks: [
      { id: "m16-q", kind: "question", body: "Conte a cadeia da etapa 2 sem nomear um vilão molecular." },
      { id: "m16-a", kind: "answer", body: "Informação → circuitos → avaliação de relevância → alterações corporais (autonômicas e, conforme o tempo, HPA) → aprendizagem (incluindo predição) → comportamento. Emoção atravessa essa cadeia; não a inicia como um botão." },
      { id: "m16-m", kind: "mechanism", title: "Checklist de recusas", steps: [
        { id: "1", title: "Não uma área", body: "Emoção como processo." },
        { id: "2", title: "Não um personagem", body: "Dopamina e cortisol sem essência psicológica." },
        { id: "3", title: "Não uma fita", body: "Memória modulada e reconstrutiva." },
        { id: "4", title: "Não um diagnóstico", body: "Mecanismo geral ≠ a sua biografia." },
      ]},
      { id: "m16-r", kind: "recall", body: "Onde, nesta cadeia, os mecanismos da etapa 1 ainda estão presentes?" },
    ],
    misconceptions: [{ claim: "Etapa 2 substitui a etapa 1.", whyPlausible: "Falamos de sistemas e o celular parece distante.", problem: "Sem membrana, não há circuito real.", better: "Os mecanismos celulares continuam como fundamento." }],
    integration: "A etapa 3 descreve atenção, memória e decisão como outro nível — não como biologia alternativa.",
    relatedModules: ["module_08", "module_24"],
    questions: [
      q({ id: "m16-q1", moduleId: "module_16", conceptIds: ["emotion_as_process"], type: "integration", difficulty: 2, prompt: "Qual cadeia é a mais fiel à etapa 2?", options: [{ id: "a", text: "Amígdala → medo → comportamento, sempre." }, { id: "b", text: "Informação → circuitos → avaliação → corpo → aprendizagem → comportamento." }], correctAnswer: "b", explanation: "O fecho pedido pelo manuscrito.", hint1: "Não comece numa área.", hint2: "Inclua corpo e aprendizagem.", hint3: "A opção longa." }),
      q({ id: "m16-q2", moduleId: "module_16", conceptIds: ["distributed_systems"], type: "limit", difficulty: 1, prompt: "Podemos reduzir emoção a uma região?", options: [{ id: "a", text: "Sim, para simplificar sempre." }, { id: "b", text: "Não. Simplificar no início pode ser didático; o modelo final recusa a redução." }], correctAnswer: "b", explanation: "O manuscrito permite simplificação inicial, não o modelo final.", hint1: "Modelo final.", hint2: "Recusa.", hint3: "Distribuído." }),
      q({ id: "m16-q3", moduleId: "module_16", conceptIds: ["dopamine", "cortisol"], type: "misconception", difficulty: 2, prompt: "O que dopamina e cortisol têm em comum neste curso?", options: [{ id: "a", text: "Ambos são personagens de estados mentais." }, { id: "b", text: "Ambos exigem circuito, tempo, dose e contexto — e recusam personificação." }], correctAnswer: "b", explanation: "Transferência de habilidade, não de slogan.", hint1: "Anti-personagem.", hint2: "Contexto.", hint3: "Dois exemplos da mesma regra.", errorKind: "language" }),
      q({ id: "m16-q4", moduleId: "module_16", conceptIds: ["levels_of_analysis"], type: "recall", difficulty: 2, prompt: "Onde a etapa 1 permanece visível na etapa 2?", correctAnswer: "open", modelAnswer: "Em cada sinapse dos circuitos, na transdução autonômica e na ação de neuromoduladores via receptores — o chão celular não foi aposentado.", explanation: "Fundamento, não substituição.", hint1: "Receptores.", hint2: "Circuitos são células.", hint3: "Não aposentou." }),
      q({ id: "m16-q5", moduleId: "module_16", conceptIds: ["distributed_systems", "emotion_as_process"], type: "counterfactual", difficulty: 2, prompt: "Se removêssemos o componente corporal da cadeia sistêmica (autonômico, endócrino, interocepção), a explicação de um episódio afetivo:", options: [{ id: "a", text: "Ficaria intacta: o cérebro basta." }, { id: "b", text: "Perderia efetores, temporalidades e sinais que participam da avaliação e do aprendizado — o organismo não é uma dispensa opcional." }], correctAnswer: "b", explanation: "Cadeia sistêmica exige o corpo.", hint1: "Efetores.", hint2: "Interocepção.", hint3: "Não é opcional.", errorKind: "scale" }),
    ],
    summary: { shouldKnow: ["Recitar a cadeia sistêmica.", "Manter as recusas (área, personagem, fita, diagnóstico)."], acquiredConcepts: ["distributed_systems", "emotion_as_process"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
];
