import type { ModuleContent } from "../types.ts";

const mastery = {
  comprehension: 70,
  recall: 70,
  contrast: 70,
  application: 60,
};

export const STAGE_1_MODULES: ModuleContent[] = [
  {
    id: "module_01",
    stage: 1,
    number: 1,
    title: "O sistema nervoso como sistema biológico",
    shortTitle: "Sistema biológico",
    objective:
      "Compreender o sistema nervoso como tecido vivo organizado em níveis, não como um mapa de 'uma área para cada função'.",
    centralQuestion:
      "Como uma estrutura biológica composta por células consegue produzir percepção, movimento, memória e comportamento?",
    prerequisites: [],
    estimatedTime: { essential: 8, deepen: 6, questions: 5 },
    concepts: ["nervous_system", "levels_of_analysis", "evidence_vs_hypothesis"],
    introduction:
      "Antes de nomear estruturas, precisamos de uma pergunta melhor do que 'qual parte faz o quê?'. Este módulo estabelece a escala em que vamos pensar: do íon à interação social, sem fingir que um nível explica automaticamente o outro.",
    blocks: [
      {
        id: "m01-q",
        kind: "question",
        body: "Como uma estrutura biológica composta por células consegue produzir percepção, movimento, memória e comportamento?",
      },
      {
        id: "m01-a",
        kind: "answer",
        title: "Resposta inicial",
        body: "Não porque existe uma parte do cérebro para cada função. Porque células especializadas organizam-se em circuitos e sistemas, em várias escalas, acopladas a um corpo e a um contexto.",
      },
      {
        id: "m01-e",
        kind: "explain",
        title: "Organização em escalas",
        body: "Uma afirmação sobre [[levels_of_analysis|níveis de análise]] precisa declarar em que escala opera. Íons não 'são' decisões. Decisões não substituem canais. O salto indevido entre escalas é uma das fontes mais comuns de neuromitos.",
        conceptIds: ["levels_of_analysis"],
        level: "system",
      },
      {
        id: "m01-levels",
        kind: "diagram",
        title: "Sete níveis que não se fundem",
        body: "Molecular · celular · circuito · sistema · cognitivo · comportamental · social. Cada um responde a perguntas diferentes. Nenhum é 'mais verdadeiro' por ser menor.",
        diagram: "levels",
        conceptIds: ["levels_of_analysis"],
      },
      {
        id: "m01-bio",
        kind: "explain",
        title: "Tecido vivo, não hardware",
        body: "O [[nervous_system|sistema nervoso]] consome energia, depende de membranas, de glia, de sangue, de hormônios. Modelos de informação são úteis, mas o órgão não é um computador de silício. Quando o modelo ajudar, diremos que é um modelo.",
        conceptIds: ["nervous_system"],
        level: "system",
      },
      {
        id: "m01-recall",
        kind: "recall",
        title: "Pare por alguns segundos",
        body: "O que você acabou de estabelecer que a trilha inteira vai recusar? Tente dizer com suas palavras, sem olhar o bloco anterior.",
      },
      {
        id: "m01-ev",
        kind: "limit",
        title: "Observado, inferido, hipotético",
        body: "Toda afirmação importante deve distinguir: o que foi observado, o que se interpreta, e o que ainda não se pode concluir. [[evidence_vs_hypothesis|Evidência versus hipótese]] é uma habilidade, não um detalhe acadêmico.",
        conceptIds: ["evidence_vs_hypothesis"],
        layer: 2,
      },
      {
        id: "m01-adv",
        kind: "explain",
        title: "Por que isso importa agora",
        body: "Se começarmos localizando funções em áreas, cada módulo seguinte vai parecer uma lista. Se começarmos por mecanismos e níveis, cada módulo seguinte responde a uma pergunta que o anterior abriu.",
        layer: 3,
      },
    ],
    misconceptions: [
      {
        claim: "Existe uma parte do cérebro para cada função.",
        whyPlausible: "Lesões e exames mostram especialização, e mapas coloridos são fáceis de lembrar.",
        problem: "Especialização relativa não é exclusividade. Participação não é suficiência. Funções complexas são distribuídas.",
        better:
          "Redes e circuitos contribuem de modos distintos; localizar uma contribuição não esgota a função.",
      },
    ],
    integration:
      "Este módulo não ensina ainda o neurônio. Ensina a recusar o atalho. O próximo pergunta: que célula torna a sinalização possível?",
    relatedModules: ["module_02", "module_09", "module_10"],
    questions: [
      {
        id: "m01-q1",
        moduleId: "module_01",
        conceptIds: ["levels_of_analysis"],
        type: "misconception",
        difficulty: 1,
        prompt: "Qual formulação é mais cientificamente adequada?",
        options: [
          { id: "a", text: "Cada função humana tem uma área exclusiva responsável por ela." },
          { id: "b", text: "Funções podem ser descritas em vários níveis; uma estrutura pode participar sem ser suficiente." },
          { id: "c", text: "Se uma área acende no exame, ela é a causa da experiência." },
        ],
        correctAnswer: "b",
        whyPlausible: "Mapas e cores sugerem um dicionário área–função.",
        misconception: "Localização absoluta.",
        explanation:
          "A opção B preserva especialização sem transformar participação em causa exclusiva. A opção C confunde correlação hemodinâmica com causalidade.",
        hint1: "Pense na diferença entre participar e ser suficiente.",
        hint2: "Um nível de descrição não substitui outro.",
        hint3: "A frase útil contém 'participa' e 'não é suficiente'.",
        errorKind: "scale",
      },
      {
        id: "m01-q2",
        moduleId: "module_01",
        conceptIds: ["evidence_vs_hypothesis"],
        type: "limit",
        difficulty: 2,
        prompt:
          "Se uma estrutura participa de um processo, podemos concluir que ela é suficiente para produzi-lo?",
        options: [
          { id: "a", text: "Sim, participação implica suficiência." },
          { id: "b", text: "Não necessariamente. Participação não implica suficiência." },
        ],
        correctAnswer: "b",
        explanation:
          "Esta pergunta de limite reaparece na trilha. É uma das defesas contra neuromitologia.",
        hint1: "Lesão que prejudica uma função não prova que só aquela estrutura a realiza.",
        hint2: "Pense em uma orquestra: tirar o oboé muda a peça; o oboé não é a sinfonia.",
        hint3: "A resposta correta recusa o salto.",
        errorKind: "causal",
      },
      {
        id: "m01-q3",
        moduleId: "module_01",
        conceptIds: ["nervous_system"],
        type: "recall",
        difficulty: 1,
        prompt:
          "Por que não basta tratar o sistema nervoso como um computador abstrato?",
        hint1: "O que um tecido vivo precisa que um diagrama de fluxo não precisa?",
        hint2: "Energia, membranas, glia, corpo.",
        hint3: "É biológico antes de ser 'informacional'.",
        correctAnswer: "open",
        modelAnswer:
          "Porque é tecido vivo: depende de energia, íons, células de suporte e do organismo. Modelos de informação ajudam, mas não substituem a biologia.",
        explanation:
          "O modelo computacional pode ser útil se for marcado como modelo. O erro é ontologizá-lo.",
      },
      {
        id: "m01-q4",
        moduleId: "module_01",
        conceptIds: ["levels_of_analysis"],
        type: "application",
        difficulty: 2,
        prompt:
          "Alguém diz: 'ele gritou porque o sódio entrou no neurônio'. Qual é o problema principal dessa frase?",
        options: [
          { id: "a", text: "Sódio nunca entra em neurônios." },
          { id: "b", text: "Ela salta do nível molecular/celular para o comportamental como se fosse a mesma explicação." },
          { id: "c", text: "Gritos não envolvem o sistema nervoso." },
        ],
        correctAnswer: "b",
        explanation:
          "Pode haver influxo de Na⁺ em muitos disparos; isso não constitui uma explicação do episódio social. É um erro de escala.",
        hint1: "A frase mistura dois níveis distantes.",
        hint2: "Não é que o sódio seja irrelevante em algum sentido físico.",
        hint3: "O problema é tratar um nível como causa completa de outro.",
        errorKind: "scale",
      },
      {
        id: "m01-q5",
        moduleId: "module_01",
        conceptIds: ["evidence_vs_hypothesis"],
        type: "recognition",
        difficulty: 1,
        prompt:
          "Diante de uma afirmação forte sobre o cérebro, uma leitura responsável começa por:",
        options: [
          { id: "a", text: "Aceitar se vier de uma revista popular." },
          { id: "b", text: "Separar o que foi observado, o que foi inferido e o que ainda é hipótese." },
          { id: "c", text: "Rejeitar tudo que soar contraintuitivo." },
        ],
        correctAnswer: "b",
        explanation: "Habilidade central da trilha; retorna na etapa 4 como critério de aplicação.",
        hint1: "Três camadas.",
        hint2: "Nem crédito automático, nem descrédito automático.",
        hint3: "Observado, inferido, hipotético.",
      },
    ],
    summary: {
      shouldKnow: [
        "Explicar o que é um nível de análise e por que níveis não se substituem.",
        "Recusar o mapa 'uma área = uma função' como modelo final.",
        "Distinguir observado, inferido e hipotético.",
      ],
      acquiredConcepts: ["levels_of_analysis", "nervous_system", "evidence_vs_hypothesis"],
    },
    masteryCriteria: mastery,
    references: [
      { title: "Kandel et al., Principles of Neural Science", kind: "livro", note: "visão sistêmica e celular" },
      { title: "Craver, Explaining the Brain", kind: "livro", note: "níveis e mecanismos" },
    ],
    contentVersion: "1.0",
  },
  {
    id: "module_02",
    stage: 1,
    number: 2,
    title: "O neurônio",
    shortTitle: "Neurônio",
    objective:
      "Relacionar a forma do neurônio (dendritos, soma, axônio, terminal) à direção do fluxo de sinais.",
    centralQuestion: "Como a estrutura de uma célula permite receber e transmitir sinais?",
    prerequisites: ["module_01"],
    estimatedTime: { essential: 8, deepen: 6, questions: 5 },
    concepts: ["neuron", "dendrite", "soma", "axon", "axon_terminal", "glia"],
    introduction:
      "Você já tem a pergunta da escala. Agora olhamos a célula que torna a sinalização elétrica e química possível. A forma não é enfeite: é restrição funcional.",
    blocks: [
      {
        id: "m02-q",
        kind: "question",
        body: "Como a estrutura de uma célula permite receber e transmitir sinais?",
      },
      {
        id: "m02-a",
        kind: "answer",
        title: "Resposta inicial",
        body: "O [[neuron|neurônio]] é polarizado: recebe em dendritos e soma, conduz pelo [[axon|axônio]], comunica no [[axon_terminal|terminal]]. Essa assimetria espacial é o começo da direção da informação.",
        conceptIds: ["neuron"],
      },
      {
        id: "m02-parts",
        kind: "mechanism",
        title: "Partes e papéis",
        conceptIds: ["dendrite", "soma", "axon", "axon_terminal"],
        steps: [
          { id: "d", title: "Dendritos", body: "Aumentam superfície de recepção. Entradas sinápticas chegam aqui com mais frequência." },
          { id: "s", title: "Soma", body: "Núcleo, metabolismo e parte da integração. Não é 'o neurônio inteiro'." },
          { id: "a", title: "Axônio", body: "Condução a distância. Diâmetro e mielina mudam a velocidade." },
          { id: "t", title: "Terminal", body: "Conversão de sinal elétrico em evento químico, na maioria das sinapses." },
        ],
      },
      {
        id: "m02-glia",
        kind: "explain",
        title: "A glia não é cola",
        body: "[[glia|Células gliais]] mielinizam, sustentam metabolismo, participam de homeostase iônica e de respostas imunes. Ignorá-las empobrece qualquer modelo de condução ou de sinapse.",
        conceptIds: ["glia"],
        layer: 2,
      },
      {
        id: "m02-recall",
        kind: "recall",
        body: "Se você desenhasse um neurônio agora, o que cada prolongamento estaria fazendo — não só como se chama?",
      },
      {
        id: "m02-div",
        kind: "explain",
        title: "Diversidade",
        body: "Não existe 'o' neurônio típico universal. Há células de projeção, interneurônios, células sensoriais. O esquema polarizado é um modelo de partida, não a fotografia de todas as células.",
        layer: 3,
      },
    ],
    misconceptions: [
      {
        claim: "O neurônio é um fio que leva eletricidade como cobre.",
        whyPlausible: "Falamos em 'impulsos' e desenhos escolares parecem cabos.",
        problem: "A condução é um evento de membrana, regenerativo, com metabolismo e polaridade química no terminal.",
        better: "É uma célula cuja membrana produz e propaga um sinal, e cujo terminal em geral libera transmissor.",
      },
    ],
    integration:
      "A forma aponta para a membrana: é nela que a diferença elétrica vai nascer. O próximo módulo pergunta de onde vem essa diferença.",
    relatedModules: ["module_03", "module_05", "module_06"],
    questions: [
      {
        id: "m02-q1",
        moduleId: "module_02",
        conceptIds: ["neuron"],
        type: "relation",
        difficulty: 1,
        prompt: "Qual sequência descreve melhor a polaridade típica de um neurônio de projeção?",
        options: [
          { id: "a", text: "Terminal → axônio → dendritos" },
          { id: "b", text: "Dendritos/soma recebem; axônio conduz; terminal comunica" },
          { id: "c", text: "O soma dispara luz que o axônio reflete" },
        ],
        correctAnswer: "b",
        explanation: "A polaridade espacial é o primeiro modelo da direção do sinal.",
        hint1: "Onde costumam chegar as sinapses de entrada?",
        hint2: "O axônio é o caminho longo.",
        hint3: "O terminal é o fim daquele caminho.",
      },
      {
        id: "m02-q2",
        moduleId: "module_02",
        conceptIds: ["axon_terminal"],
        type: "recall",
        difficulty: 1,
        prompt: "O que o terminal axônico permite que o axônio, sozinho, não realiza na sinapse química típica?",
        correctAnswer: "open",
        modelAnswer:
          "Converter o sinal elétrico em liberação química (em geral dependente de Ca²⁺) para influenciar outra célula.",
        explanation: "O axônio propaga; o terminal transduz.",
        hint1: "Pense em conversão de código, não em mais comprimento.",
        hint2: "Elétrico → químico.",
        hint3: "Vesículas e transmissor entram na história no terminal.",
      },
      {
        id: "m02-q3",
        moduleId: "module_02",
        conceptIds: ["glia"],
        type: "misconception",
        difficulty: 2,
        prompt: "Qual afirmação sobre a glia é mais adequada?",
        options: [
          { id: "a", text: "É apenas enchimento entre neurônios." },
          { id: "b", text: "Participa de mielinização, suporte metabólico e homeostase, entre outras funções." },
          { id: "c", text: "Substitui os neurônios em todas as funções cognitivas." },
        ],
        correctAnswer: "b",
        explanation: "Nem cola, nem protagonista exclusivo. Participação específica.",
        hint1: "O nome histórico 'glue' é o erro.",
        hint2: "Mielina é feita por glia.",
        hint3: "Escolha a participação concreta.",
        errorKind: "factual",
      },
      {
        id: "m02-q4",
        moduleId: "module_02",
        conceptIds: ["neuron"],
        type: "counterfactual",
        difficulty: 2,
        prompt:
          "Se um neurônio perdesse a polaridade espacial (sinapses de entrada e saída misturadas sem axônio definido), o que seria imediatamente prejudicado?",
        options: [
          { id: "a", text: "A possibilidade de conduzir um sinal a distância de forma dirigida" },
          { id: "b", text: "A existência de DNA no núcleo" },
          { id: "c", text: "A gravidade sobre o encéfalo" },
        ],
        correctAnswer: "a",
        explanation: "A forma é restrição da direção. Sem ela, o modelo de 'receber aqui, enviar ali' desaba.",
        hint1: "O que a assimetria espacial garante?",
        hint2: "Não é o metabolismo básico.",
        hint3: "Condução dirigida a distância.",
        errorKind: "causal",
      },
      {
        id: "m02-q5",
        moduleId: "module_02",
        conceptIds: ["neuron", "glia"],
        type: "application",
        difficulty: 2,
        prompt:
          "Diante de um texto de divulgação que descreve o encéfalo como 'uma rede de neurônios', a leitura mais precisa acrescenta:",
        options: [
          { id: "a", text: "Que glia é apenas suporte passivo e pode ser omitida." },
          { id: "b", text: "Que glia participa ativamente (mielinização, sinalização, sustentação) e faz parte da rede funcional." },
          { id: "c", text: "Que só a quantidade de neurônios importa para explicar comportamento." },
        ],
        correctAnswer: "b",
        explanation: "Precisão didática: rede = neurônios + glia; nomear a participação evita reducionismo.",
        hint1: "Quem faz mielina?",
        hint2: "Suporte não é sinônimo de irrelevante.",
        hint3: "Rede funcional inclui os dois tipos.",
        errorKind: "generalization",
      },
    ],
    summary: {
      shouldKnow: [
        "Nomear dendrito, soma, axônio e terminal pelo papel, não só pelo desenho.",
        "Incluir a glia no modelo de tecido nervoso.",
        "Tratar a polaridade como condição da comunicação a distância.",
      ],
      acquiredConcepts: ["neuron", "dendrite", "soma", "axon", "axon_terminal", "glia"],
    },
    masteryCriteria: mastery,
    references: [
      { title: "Kandel et al., Principles of Neural Science", kind: "livro" },
      { title: "Purves et al., Neuroscience", kind: "livro" },
    ],
    contentVersion: "1.0",
  },
  {
    id: "module_03",
    stage: 1,
    number: 3,
    title: "Membrana e potencial de repouso",
    shortTitle: "Potencial de repouso",
    objective:
      "Explicar de onde surge a diferença elétrica através da membrana, sem atribuí-la a um único íon ou à bomba como 'choque'.",
    centralQuestion: "De onde surge a diferença elétrica?",
    prerequisites: ["module_02"],
    estimatedTime: { essential: 10, deepen: 7, questions: 5 },
    concepts: [
      "membrane",
      "ion_gradient",
      "sodium_potassium_pump",
      "membrane_potential",
      "resting_potential",
      "electrochemical_equilibrium",
    ],
    introduction:
      "Até aqui, a célula tem forma. Agora precisamos da física da membrana: assimetrias de íons, permeabilidade seletiva e um potencial em repouso. Sem isso, o potencial de ação não tem palco.",
    blocks: [
      {
        id: "m03-q",
        kind: "question",
        body: "De onde surge a diferença elétrica entre os dois lados da membrana?",
      },
      {
        id: "m03-a",
        kind: "answer",
        title: "Resposta inicial",
        body: "De [[ion_gradient|gradientes iônicos]] mantidos a custo energético e da permeabilidade seletiva da [[membrane|membrana]]. O potencial não é um 'fluido elétrico' estocado no citoplasma.",
        conceptIds: ["ion_gradient", "membrane"],
      },
      {
        id: "m03-mech",
        kind: "mechanism",
        title: "O que precisa existir",
        steps: [
          { id: "g", title: "Assimetria", body: "Na⁺ mais fora, K⁺ mais dentro — energia potencial química." },
          { id: "p", title: "Permeabilidade", body: "No repouso, a membrana é mais permeável a K⁺ do que a Na⁺." },
          { id: "e", title: "Equilíbrio de um íon", body: "Cada íon tem um potencial de equilíbrio (Nernst). Não confundir com o potencial da célula." },
          { id: "r", title: "Repouso", body: "O potencial de repouso é um compromisso ponderado pelas permeabilidades, com contribuição da bomba." },
        ],
        conceptIds: ["electrochemical_equilibrium", "resting_potential"],
      },
      {
        id: "m03-pump",
        kind: "explain",
        title: "O que a bomba faz — e o que não faz",
        body: "A [[sodium_potassium_pump|bomba Na⁺/K⁺]] restabelece gradientes. Ela não é o gerador instantâneo do potencial de ação. Confundi-las é um erro causal clássico.",
        conceptIds: ["sodium_potassium_pump"],
      },
      {
        id: "m03-recall",
        kind: "recall",
        body: "Se os canais de K⁺ de repouso deixassem de existir, o potencial da célula continuaria idêntico? Por quê?",
      },
      {
        id: "m03-goldman",
        kind: "explain",
        title: "Goldman, em uma frase",
        body: "O potencial da membrana é uma média ponderada dos potenciais de equilíbrio dos íons, pesos = permeabilidades. Mude a permeabilidade, e o potencial se move — essa será a lógica do módulo 4.",
        layer: 2,
        conceptIds: ["membrane_potential"],
      },
    ],
    misconceptions: [
      {
        claim: "O interior é negativo só porque há proteínas negativas.",
        whyPlausible: "Há ânions orgânicos impermeáveis, e isso conta.",
        problem: "Sem gradientes e sem permeabilidades seletivas, essa observação não explica o valor do potencial nem sua dinâmica.",
        better: "O potencial resulta de assimetrias iônicas e de permeabilidades; ânions impermeáveis entram no quadro, mas não o esgotam.",
      },
    ],
    integration:
      "A membrana mantém diferenças. O próximo módulo pergunta o que acontece quando essas diferenças deixam de permanecer estáveis e a membrana muda rapidamente de estado.",
    relatedModules: ["module_04", "module_07"],
    questions: [
      {
        id: "m03-q1",
        moduleId: "module_03",
        conceptIds: ["resting_potential"],
        type: "recognition",
        difficulty: 1,
        prompt: "O potencial de repouso é melhor descrito como:",
        options: [
          { id: "a", text: "O equilíbrio exclusivo do sódio." },
          { id: "b", text: "Um compromisso determinado por gradientes e permeabilidades, próximo ao equilíbrio do potássio, mas não idêntico a ele." },
          { id: "c", text: "A voltagem da bomba disparando o tempo todo como um gerador." },
        ],
        correctAnswer: "b",
        explanation: "Próximo ao K⁺, não idêntico. A bomba contribui, mas não 'é' o potencial instantâneo.",
        hint1: "Qual íon tem maior permeabilidade no repouso?",
        hint2: "Não escolha um único íon como dono do número.",
        hint3: "Compromisso, não identidade.",
      },
      {
        id: "m03-q2",
        moduleId: "module_03",
        conceptIds: ["sodium_potassium_pump"],
        type: "misconception",
        difficulty: 2,
        prompt: "Qual papel da bomba é o mais preciso neste módulo?",
        options: [
          { id: "a", text: "Ela produz cada potencial de ação." },
          { id: "b", text: "Ela mantém os gradientes sem os quais as correntes de canal não se sustentam ao longo do tempo." },
          { id: "c", text: "Ela é irrelevante porque os canais fazem tudo." },
        ],
        correctAnswer: "b",
        explanation: "Manutenção versus evento rápido: duas escalas temporais.",
        hint1: "ATP entra na história da manutenção.",
        hint2: "O evento de milissegundos é canal, não bomba.",
        hint3: "Gradientes, não o spike.",
        errorKind: "causal",
      },
      {
        id: "m03-q3",
        moduleId: "module_03",
        conceptIds: ["electrochemical_equilibrium"],
        type: "counterfactual",
        difficulty: 2,
        prompt:
          "Se a membrana se tornasse igualmente permeável a Na⁺ e K⁺ de repente, o potencial de repouso típico:",
        options: [
          { id: "a", text: "Permaneceria exatamente o mesmo, porque os gradientes não mudaram ainda." },
          { id: "b", text: "Deslocaria-se, porque o potencial depende das permeabilidades relativas, não só das concentrações." },
          { id: "c", text: "A célula explodiria imediatamente por falta de DNA." },
        ],
        correctAnswer: "b",
        explanation: "Concentrações ainda estariam lá; os pesos da média mudaram. Esse é o germe do potencial de ação.",
        hint1: "Goldman: pesos = permeabilidades.",
        hint2: "O módulo 4 vai usar exatamente essa ideia.",
        hint3: "O potencial se move se a permeabilidade se move.",
        errorKind: "causal",
      },
      {
        id: "m03-q4",
        moduleId: "module_03",
        conceptIds: ["ion_gradient"],
        type: "recall",
        difficulty: 1,
        prompt: "Explique, sem consultar, de onde surge a diferença elétrica.",
        correctAnswer: "open",
        modelAnswer:
          "De assimetrias de concentração iônica mantidas a custo energético e da permeabilidade seletiva da membrana, que permitem fluxos líquidos até um potencial de compromisso.",
        explanation: "Se a resposta citar só 'proteínas negativas' ou só 'a bomba dispara', o modelo ainda está incompleto.",
        hint1: "Dois ingredientes: assimetria e seletividade.",
        hint2: "A bomba mantém; os canais deixam fluir.",
        hint3: "Potencial = compromisso.",
      },
      {
        id: "m03-q5",
        moduleId: "module_03",
        conceptIds: ["resting_potential"],
        type: "application",
        difficulty: 2,
        prompt:
          "Um bloqueio parcial da bomba Na⁺/K⁺ por horas produziria, previsivelmente:",
        options: [
          { id: "a", text: "Nenhum efeito, porque os canais é que fazem o potencial." },
          { id: "b", text: "Erosão gradual dos gradientes iônicos e drift do potencial de repouso ao longo do tempo." },
          { id: "c", text: "Aumento imediato da amplitude do potencial de ação." },
        ],
        correctAnswer: "b",
        explanation: "Sem manutenção ativa, os gradientes que a permeabilidade transforma em voltagem se degradam.",
        hint1: "Canais gastam gradiente; a bomba repõe.",
        hint2: "Sem reposição, o estoque cai.",
        hint3: "O potencial é sustentado por energia.",
        errorKind: "causal",
      },
    ],
    summary: {
      shouldKnow: [
        "Separar potencial de equilíbrio de um íon e potencial de repouso da célula.",
        "Dizer o que a bomba faz e o que ela não faz.",
        "Antecipar que mudar permeabilidade muda o potencial.",
      ],
      acquiredConcepts: [
        "membrane",
        "ion_gradient",
        "sodium_potassium_pump",
        "membrane_potential",
        "resting_potential",
        "electrochemical_equilibrium",
      ],
    },
    masteryCriteria: mastery,
    references: [
      { title: "Hodgkin & Huxley, 1952 (base histórica)", kind: "artigo" },
      { title: "Boron & Boulpaep, Medical Physiology", kind: "livro" },
    ],
    contentVersion: "1.0",
  },
  {
    id: "module_04",
    stage: 1,
    number: 4,
    title: "Como o sinal elétrico se origina",
    shortTitle: "Potencial de ação",
    objective:
      "Compreender como alterações na membrana produzem o potencial de ação: limiar, Na⁺, despolarização, K⁺, repolarização, refratário, tudo-ou-nada.",
    centralQuestion: "O que acontece quando a diferença elétrica muda rapidamente?",
    prerequisites: ["module_02", "module_03"],
    estimatedTime: { essential: 10, deepen: 7, questions: 6 },
    concepts: [
      "threshold",
      "depolarization",
      "sodium_channels",
      "repolarization",
      "potassium_channels",
      "hyperpolarization",
      "refractory_period",
      "all_or_none",
      "action_potential",
    ],
    introduction:
      "Até aqui, você aprendeu que a membrana mantém diferenças de concentração entre os dois lados. Agora precisamos entender o que acontece quando essas diferenças deixam de permanecer estáveis e a membrana muda rapidamente de estado.",
    blocks: [
      {
        id: "m04-q",
        kind: "question",
        body: "Como uma célula consegue produzir um sinal elétrico?",
      },
      {
        id: "m04-a",
        kind: "answer",
        title: "Resposta inicial",
        body: "Abrindo, de forma dependente de voltagem, [[sodium_channels|canais de Na⁺]] quando o potencial se aproxima de um [[threshold|limiar]]. A entrada de Na⁺ despolariza mais, o que abre mais canais — um ciclo regenerativo chamado [[action_potential|potencial de ação]].",
        alt: "De outra maneira: o estímulo não 'injeta eletricidade' como um cabo. Ele muda a probabilidade de canais de Na⁺ se abrirem. Quando essa corrente vence as que puxam ao repouso, o evento se sustenta sozinho por uns instantes.",
        conceptIds: ["action_potential"],
      },
      {
        id: "m04-diag",
        kind: "diagram",
        title: "As fases, pausáveis",
        body: "Repouso → limiar → Na⁺ entra → despolarização → K⁺ e inativação de Na⁺ → repolarização → período refratário → retorno. Toque cada etapa.",
        diagram: "action_potential",
      },
      {
        id: "m04-mech",
        kind: "mechanism",
        title: "O que muda fisicamente",
        steps: [
          { id: "t", title: "Limiar", body: "Corrente de Na⁺ vence as correntes que puxam ao repouso." },
          { id: "na", title: "Despolarização", body: "Influxo de Na⁺ torna o interior menos negativo, eventualmente positivo." },
          { id: "in", title: "Inativação", body: "Canais de Na⁺ inativam; o ciclo positivo se encerra." },
          { id: "k", title: "Repolarização", body: "K⁺ sai por canais que se abriram com a despolarização." },
          { id: "r", title: "Refratário", body: "Enquanto Na⁺ está inativado, um novo spike é impossível ou difícil — e a propagação ganha direção." },
        ],
      },
      {
        id: "m04-all",
        kind: "explain",
        title: "Tudo-ou-nada, com cuidado",
        body: "Uma vez no limiar, a amplitude do evento regenerativo não escala com o estímulo que o disparou. Isso não apaga potenciais graduados em dendritos. [[all_or_none|Tudo-ou-nada]] descreve o spike axônico clássico, não a vida inteira da célula.",
        conceptIds: ["all_or_none"],
      },
      {
        id: "m04-recall",
        kind: "recall",
        body: "Sem consultar: por que a bomba não é a causa imediata da fase ascendente?",
      },
      {
        id: "m04-hyp",
        kind: "explain",
        title: "Hiperpolarização pós-potencial",
        body: "Às vezes o potencial ultrapassa o repouso ([[hyperpolarization|hiperpolarização]]). Isso é um estado elétrico transitório, não um desligamento da célula.",
        conceptIds: ["hyperpolarization"],
        layer: 2,
      },
    ],
    misconceptions: [
      {
        claim: "O potencial de ação é a bomba ligando e desligando.",
        whyPlausible: "A bomba é famosa e envolve Na⁺ e K⁺, os mesmos íons do spike.",
        problem: "Escala temporal e mecanismo: o spike é canal dependente de voltagem; a bomba é manutenção.",
        better: "Canais de Na⁺ e K⁺ dependentes de voltagem geram o evento; a bomba preserva os gradientes.",
      },
    ],
    integration:
      "O sinal nasceu. Ainda não viajou. O módulo 5 pergunta como essa mudança chega ao final do axônio.",
    relatedModules: ["module_03", "module_05", "module_06"],
    questions: [
      {
        id: "m04-q1",
        moduleId: "module_04",
        conceptIds: ["action_potential", "sodium_channels"],
        type: "counterfactual",
        difficulty: 2,
        prompt:
          "Se a membrana não possuísse canais de Na⁺ dependentes de voltagem funcionais, o que aconteceria com a geração do potencial de ação clássico?",
        options: [
          { id: "a", text: "Nada: a bomba compensaria na hora." },
          { id: "b", text: "O ciclo regenerativo da fase ascendente não se sustentaria." },
          { id: "c", text: "O neurônio se tornaria uma célula muscular." },
        ],
        correctAnswer: "b",
        explanation: "Sem I_Na regenerativo, não há spike clássico. Há outros eventos elétricos possíveis, mas não esse mecanismo.",
        hint1: "Qual corrente sobe a fase ascendente?",
        hint2: "A bomba não substitui o canal na milissegundo.",
        hint3: "Sem Na⁺ voltage-gated, sem ciclo positivo.",
        errorKind: "causal",
      },
      {
        id: "m04-q2",
        moduleId: "module_04",
        conceptIds: ["refractory_period"],
        type: "relation",
        difficulty: 2,
        prompt: "O período refratário importa para a propagação porque:",
        options: [
          { id: "a", text: "Impede que o trecho recém-ativo seja imediatamente reexcitado, contribuindo para a direção do sinal." },
          { id: "b", text: "É o momento em que a dopamina é liberada no axônio." },
          { id: "c", text: "Apaga a memória da pessoa." },
        ],
        correctAnswer: "a",
        explanation: "Inativação de Na⁺ + condutância de K⁺ = janela em que um novo spike falha. Isso dá seta ao avanço.",
        hint1: "Pense no trecho que acabou de disparar.",
        hint2: "Ele pode ser reexcitado imediatamente?",
        hint3: "Direção, não humor.",
      },
      {
        id: "m04-q3",
        moduleId: "module_04",
        conceptIds: ["all_or_none"],
        type: "misconception",
        difficulty: 2,
        prompt: "Tudo-ou-nada significa que:",
        options: [
          { id: "a", text: "Neurônios não têm nenhum sinal graduado." },
          { id: "b", text: "O evento regenerativo axônico clássico, uma vez no limiar, não escala sua amplitude com a força do estímulo disparador." },
          { id: "c", text: "A pessoa ou está 100% atenta ou 0%." },
        ],
        correctAnswer: "b",
        explanation: "EPSPs são graduados. O erro é expandir a propriedade do spike para toda a fisiologia e para a psicologia.",
        hint1: "Qual evento exatamente é tudo-ou-nada?",
        hint2: "Dendritos ainda somam entradas graduadas.",
        hint3: "Spike axônico, não a vida mental.",
        errorKind: "generalization",
      },
      {
        id: "m04-q4",
        moduleId: "module_04",
        conceptIds: ["action_potential"],
        type: "recall",
        difficulty: 2,
        prompt: "Reconstrua as fases do potencial de ação a partir do limiar.",
        correctAnswer: "open",
        modelAnswer:
          "Limiar → abertura de canais de Na⁺ e influxo → despolarização → inativação de Na⁺ e abertura de K⁺ → repolarização → período refratário → retorno ao repouso (às vezes com hiperpolarização).",
        explanation: "A ordem é o mecanismo. Se inverter Na⁺ e K⁺, o modelo quebra.",
        hint1: "Quem sobe? Quem desce?",
        hint2: "Na⁺ depois inativa; K⁺ contribui para descer.",
        hint3: "Termine no refratário.",
      },
      {
        id: "m04-q5",
        moduleId: "module_04",
        conceptIds: ["repolarization"],
        type: "recognition",
        difficulty: 1,
        prompt: "A repolarização imediata deve-se principalmente a:",
        options: [
          { id: "a", text: "A bomba desligar o neurônio." },
          { id: "b", text: "Inativação dos canais de Na⁺ e efluxo de K⁺." },
          { id: "c", text: "Entrada de neurotransmissor no axônio." },
        ],
        correctAnswer: "b",
        explanation: "De novo a distinção manutenção versus evento.",
        hint1: "Milissegundos, não minutos.",
        hint2: "Canais, não ATPase como causa imediata.",
        hint3: "Na⁺ inativa, K⁺ sai.",
        errorKind: "causal",
      },
    ],
    summary: {
      shouldKnow: [
        "Reconstruir o ciclo Na⁺/K⁺ do spike.",
        "Explicar limiar, refratário e tudo-ou-nada sem expandi-los indevidamente.",
        "Separar bomba e canais no tempo.",
      ],
      acquiredConcepts: [
        "threshold",
        "depolarization",
        "sodium_channels",
        "repolarization",
        "potassium_channels",
        "hyperpolarization",
        "refractory_period",
        "all_or_none",
        "action_potential",
      ],
    },
    masteryCriteria: mastery,
    references: [
      { title: "Hodgkin & Huxley, 1952", kind: "artigo" },
      { title: "Kandel et al., Principles of Neural Science", kind: "livro" },
    ],
    contentVersion: "1.0",
  },
  {
    id: "module_05",
    stage: 1,
    number: 5,
    title: "Como o sinal chega ao fim do axônio",
    shortTitle: "Propagação",
    objective:
      "Explicar a propagação como reconstrução sucessiva do potencial de ação, e o papel de mielina e nódulos.",
    centralQuestion: "Como essa mudança chega ao final do axônio?",
    prerequisites: ["module_04"],
    estimatedTime: { essential: 8, deepen: 6, questions: 5 },
    concepts: ["propagation", "myelin", "nodes_of_ranvier", "saltatory_conduction"],
    introduction:
      "O potencial de ação é um evento local de membrana. Se ficasse no ponto em que nasceu, o terminal nunca ficaria sabendo. Este módulo trata do deslocamento — sem o mito do fio de cobre.",
    blocks: [
      {
        id: "m05-q",
        kind: "question",
        body: "Como um evento de membrana em um ponto influencia o ponto vizinho?",
      },
      {
        id: "m05-a",
        kind: "answer",
        body: "Correntes locais despolarizam o trecho adjacente até o limiar, e o spike é reconstruído. [[propagation|Propagação]] é regeneração em série, não um elétron viajando intacto pelo axoplasma.",
        conceptIds: ["propagation"],
      },
      {
        id: "m05-my",
        kind: "explain",
        title: "Mielina muda o cabo",
        body: "[[myelin|Mielina]] aumenta resistência transmembrana e reduz capacitância nos internódulos. O sinal regenera nos [[nodes_of_ranvier|nódulos de Ranvier]], ricos em canais de Na⁺ — [[saltatory_conduction|condução saltatória]].",
        conceptIds: ["myelin", "nodes_of_ranvier", "saltatory_conduction"],
      },
      {
        id: "m05-mech",
        kind: "mechanism",
        title: "O que a mielina não é",
        steps: [
          { id: "n", title: "Não é mágica", body: "Não 'acelera eletricidade' como slogan. Altera propriedades de cabo." },
          { id: "s", title: "Salto", body: "O 'salto' é o padrão de regeneração nodal, não um íon teletransportado." },
          { id: "d", title: "Desmielinização", body: "Pode falhar a chegada a tempo, ou falhar de vez — consequência clínica real." },
        ],
      },
      {
        id: "m05-recall",
        kind: "recall",
        body: "Por que o período refratário, visto no módulo 4, ajuda o sinal a não ficar ecoando no mesmo ponto?",
      },
      {
        id: "m05-speed",
        kind: "explain",
        title: "Velocidade",
        body: "Diâmetro maior e mielina aumentam velocidade. Fibras diferentes servem demandas diferentes (dor lenta versus propriocepção rápida, em linhas gerais). Não transforme isso em hierarquia moral de 'fibras melhores'.",
        layer: 2,
      },
    ],
    misconceptions: [
      {
        claim: "O axônio é um fio; a corrente segue pelo interior como em cobre.",
        whyPlausible: "A analogia elétrica é tentadora e parcialmente útil.",
        problem: "O evento é transmembrana e regenerativo. O interior participa de correntes locais, mas o 'sinal' não é um elétron livre viajando a cabo intacto.",
        better: "Modelo de cabo ativo: trechos de membrana reconstroem o spike.",
      },
    ],
    integration:
      "O spike chegou ao terminal. Surge a pergunta: como esse sinal atravessa o espaço entre duas células?",
    relatedModules: ["module_04", "module_06"],
    questions: [
      {
        id: "m05-q1",
        moduleId: "module_05",
        conceptIds: ["propagation"],
        type: "recognition",
        difficulty: 1,
        prompt: "Propagação axônica é melhor descrita como:",
        options: [
          { id: "a", text: "Um elétron único viajando pelo citoplasma até o terminal." },
          { id: "b", text: "Reconstrução sucessiva do potencial de ação ao longo da membrana." },
          { id: "c", text: "A bomba empurrando cargas como uma mangueira." },
        ],
        correctAnswer: "b",
        explanation: "Regeneração em série. Essa frase deve sobreviver a qualquer analogia.",
        hint1: "O spike é um evento de membrana.",
        hint2: "O trecho vizinho precisa chegar ao limiar.",
        hint3: "Reconstrução, não viagem de um elétron.",
      },
      {
        id: "m05-q2",
        moduleId: "module_05",
        conceptIds: ["saltatory_conduction"],
        type: "misconception",
        difficulty: 2,
        prompt: "Condução saltatória significa que:",
        options: [
          { id: "a", text: "O potencial de ação é regenerado nos nódulos, avançando de nódulo a nódulo." },
          { id: "b", text: "Íons saltam no ar entre neurônios distantes." },
          { id: "c", text: "A mielina é desnecessária se a pessoa se concentrar." },
        ],
        correctAnswer: "a",
        explanation: "Literalizar o salto é o erro. Nódulos são o lugar da regeneração.",
        hint1: "Onde estão os canais de Na⁺ densos no axônio mielinizado?",
        hint2: "Internódulo versus nódulo.",
        hint3: "Regeneração nodal.",
        errorKind: "language",
      },
      {
        id: "m05-q3",
        moduleId: "module_05",
        conceptIds: ["myelin"],
        type: "counterfactual",
        difficulty: 2,
        prompt: "Se os nódulos de Ranvier perdessem os canais de Na⁺ dependentes de voltagem, a condução saltatória:",
        options: [
          { id: "a", text: "Continuaria igual, porque a mielina basta." },
          { id: "b", text: "Falharia a regeneração nodal, comprometendo a chegada fidedigna do sinal." },
          { id: "c", text: "O dendrito assumiria a condução." },
        ],
        correctAnswer: "b",
        explanation: "Mielina sem regeneração não é o mecanismo saltatório.",
        hint1: "O que o nódulo faz que o internódulo não faz?",
        hint2: "Spike precisa de I_Na.",
        hint3: "Sem canal nodal, sem regeneração.",
        errorKind: "causal",
      },
      {
        id: "m05-q4",
        moduleId: "module_05",
        conceptIds: ["propagation"],
        type: "recall",
        difficulty: 1,
        prompt: "Por que o modelo do fio de cobre é insuficiente?",
        correctAnswer: "open",
        modelAnswer:
          "Porque o sinal é um evento regenerativo de membrana, dependente de canais, e não uma corrente metálica contínua pelo interior da célula.",
        explanation: "A analogia pode introduzir o conceito de cabo; não pode ser o modelo final.",
        hint1: "Onde está o evento: interior ou membrana?",
        hint2: "Canais.",
        hint3: "Regeneração.",
      },
      {
        id: "m05-q5",
        moduleId: "module_05",
        conceptIds: ["propagation", "myelin"],
        type: "application",
        difficulty: 2,
        prompt:
          "Em uma desmielinização inicial (mielina parcialmente comprometida), a previsão mais coerente é:",
        options: [
          { id: "a", text: "Aumento da velocidade, porque a fibra ficou mais 'nua'." },
          { id: "b", text: "Lentificação e falhas de condução, porque a regeneração salta­tória depende da integridade dos nódulos." },
          { id: "c", text: "Reversão da direção do potencial." },
        ],
        correctAnswer: "b",
        explanation: "O modelo prevê perda de eficiência; sintomas clínicos se organizam por essa lógica.",
        hint1: "Mielina otimiza; sua perda desotimiza.",
        hint2: "Nódulos são pontos de regeneração.",
        hint3: "Sem eles, o sinal fica errante.",
        errorKind: "causal",
      },
    ],
    summary: {
      shouldKnow: [
        "Descrever propagação como regeneração.",
        "Explicar mielina e nódulos sem literalizar o salto.",
        "Relacionar refratário à direção.",
      ],
      acquiredConcepts: ["propagation", "myelin", "nodes_of_ranvier", "saltatory_conduction"],
    },
    masteryCriteria: mastery,
    references: [
      { title: "Waxman, Clinical neuroanatomy of conduction", kind: "revisao" },
      { title: "Kandel et al.", kind: "livro" },
    ],
    contentVersion: "1.0",
  },
  {
    id: "module_06",
    stage: 1,
    number: 6,
    title: "A sinapse",
    shortTitle: "Sinapse",
    objective:
      "Reconstruir a cadeia do potencial no terminal até o receptor, com o Ca²⁺ no centro da liberação.",
    centralQuestion: "Como esse sinal consegue atravessar o espaço entre duas células?",
    prerequisites: ["module_04", "module_05"],
    estimatedTime: { essential: 10, deepen: 6, questions: 6 },
    concepts: [
      "synapse",
      "calcium_channels",
      "vesicles",
      "neurotransmitter",
      "synaptic_cleft",
      "receptor",
    ],
    introduction:
      "Agora que sabemos como o potencial de ação chega ao terminal axônico, surge uma pergunta: como esse sinal influencia outra célula? Na maior parte das sinapses centrais, a resposta é química.",
    blocks: [
      {
        id: "m06-q",
        kind: "question",
        body: "Qual etapa depende diretamente da entrada de Ca²⁺ no terminal?",
      },
      {
        id: "m06-a",
        kind: "answer",
        body: "A fusão das [[vesicles|vesículas]] e a liberação de [[neurotransmitter|neurotransmissor]] na [[synaptic_cleft|fenda]]. O spike pode chegar e, sem Ca²⁺, a mensagem química não sai.",
        conceptIds: ["calcium_channels", "vesicles"],
      },
      {
        id: "m06-diag",
        kind: "diagram",
        title: "Cadeia da sinapse química",
        diagram: "synapse",
        body: "Potencial de ação → terminal → canais de Ca²⁺ → entrada de Ca²⁺ → vesícula → fusão → transmissor → receptor.",
      },
      {
        id: "m06-mech",
        kind: "mechanism",
        title: "Passo a passo",
        steps: [
          { id: "1", title: "O potencial chega ao terminal", body: "Despolarização da membrana pré-sináptica." },
          { id: "2", title: "Canais de Ca²⁺ se abrem", body: "Dependentes de voltagem, no terminal." },
          { id: "3", title: "Ca²⁺ entra", body: "O íon é o acoplamento eletroquímico." },
          { id: "4", title: "Vesículas liberam transmissor", body: "Fusão dependente de Ca²⁺." },
          { id: "5", title: "O transmissor encontra receptores", body: "O efeito ainda não está decidido: depende do receptor." },
        ],
        conceptIds: ["synapse"],
      },
      {
        id: "m06-nt",
        kind: "explain",
        title: "O transmissor não é um personagem",
        body: "A molécula na fenda não 'é' uma emoção. Ela é um ligante. O próximo módulo mostra que o [[receptor|receptor]] define o tipo de efeito.",
        conceptIds: ["neurotransmitter", "receptor"],
      },
      {
        id: "m06-recall",
        kind: "recall",
        body: "Sem consultar o conteúdo: explique por que a entrada de Ca²⁺ no terminal axônico favorece a liberação de neurotransmissores.",
      },
      {
        id: "m06-elec",
        kind: "explain",
        title: "Também existem sinapses elétricas",
        body: "Junções comunicantes permitem fluxo iônico direto. São importantes em certos circuitos. O modelo químico não é o único; é o mais didático para a cadeia que estamos construindo.",
        layer: 3,
      },
    ],
    misconceptions: [
      {
        claim: "O potencial de ação atravessa a fenda como eletricidade contínua.",
        whyPlausible: "A palavra 'impulso' sugere um fio.",
        problem: "Na sinapse química há transdução: elétrico → químico → (de novo) elétrico ou metabólico na célula seguinte.",
        better: "O Ca²⁺ acopla despolarização à exocitose; o receptor lê o ligante.",
      },
    ],
    integration:
      "Você já estudou algo relacionado: receptores vão detalhar o 'e depois?'. Relaciona-se também com dopamina (módulo 14) — outra molécula, mesmos cuidados.",
    relatedModules: ["module_04", "module_07", "module_14"],
    questions: [
      {
        id: "m06-q1",
        moduleId: "module_06",
        conceptIds: ["calcium_channels"],
        type: "counterfactual",
        difficulty: 2,
        prompt:
          "Se a entrada de Ca²⁺ no terminal pré-sináptico fosse impedida, qual etapa seria diretamente afetada?",
        options: [
          { id: "a", text: "A chegada do potencial de ação ao axônio, em geral" },
          { id: "b", text: "A fusão vesicular e a liberação de transmissor" },
          { id: "c", text: "A transcrição do DNA no soma, no mesmo milissegundo" },
        ],
        correctAnswer: "b",
        explanation: "O spike pode ocorrer; a exocitose falha. Esse contrafactual é o coração do módulo.",
        hint1: "O Ca²⁺ acopla o quê a quê?",
        hint2: "Despolarização do terminal → ? → transmissor na fenda.",
        hint3: "Fusão vesicular.",
        errorKind: "causal",
      },
      {
        id: "m06-q2",
        moduleId: "module_06",
        conceptIds: ["neurotransmitter"],
        type: "misconception",
        difficulty: 1,
        prompt: "Qual afirmação descreve melhor um neurotransmissor?",
        options: [
          { id: "a", text: "Uma molécula que é, por si só, uma emoção." },
          { id: "b", text: "Um ligante cujo efeito depende do receptor, do circuito e do contexto." },
          { id: "c", text: "Um elétron que salta a fenda." },
        ],
        correctAnswer: "b",
        explanation: "Anti-personificação. O módulo 7 aprofunda o receptor.",
        hint1: "A mesma molécula pode ter efeitos opostos.",
        hint2: "Quem define o efeito imediato?",
        hint3: "O receptor.",
        errorKind: "generalization",
      },
      {
        id: "m06-q3",
        moduleId: "module_06",
        conceptIds: ["calcium_channels"],
        type: "recall",
        difficulty: 2,
        prompt: "Por que o Ca²⁺ é importante na liberação de neurotransmissores?",
        correctAnswer: "open",
        modelAnswer:
          "Porque a despolarização do terminal abre canais de Ca²⁺ dependentes de voltagem; a entrada de Ca²⁺ é o sinal que favorece a fusão das vesículas e a liberação do transmissor.",
        explanation: "Se a resposta pular para 'prazer' ou 'emoção', houve salto de nível.",
        hint1: "O que acontece quando o potencial de ação chega ao terminal?",
        hint2: "Qual íon entra através de canais dependentes de voltagem?",
        hint3: "Ca²⁺ → fusão vesicular.",
      },
      {
        id: "m06-q4",
        moduleId: "module_06",
        conceptIds: ["synapse"],
        type: "application",
        difficulty: 2,
        prompt:
          "Uma toxina impede a fusão das vesículas. O axônio ainda dispara. O que você espera na célula seguinte, na sinapse química típica?",
        options: [
          { id: "a", text: "Transmissão química drasticamente reduzida ou ausente." },
          { id: "b", text: "Potenciais de ação mais rápidos no axônio pré-sináptico." },
          { id: "c", text: "Aumento automático de mielina." },
        ],
        correctAnswer: "a",
        explanation: "Dissociação clássica: spike presente, mensagem química ausente.",
        hint1: "Qual etapa a toxina corta?",
        hint2: "O spike não é suficiente sem exocitose.",
        hint3: "A pós-sináptica não recebe o ligante.",
        errorKind: "causal",
      },
      {
        id: "m06-q5",
        moduleId: "module_06",
        conceptIds: ["synapse", "neurotransmitter"],
        type: "limit",
        difficulty: 2,
        prompt:
          "Dizer que 'a serotonina causa bem-estar' pula quais etapas da cadeia sináptica?",
        options: [
          { id: "a", text: "Nenhuma; é uma descrição direta e suficiente." },
          { id: "b", text: "Liberação, ligação a receptores específicos, efeitos pós-sinápticos e integração de circuito — o transmissor só cumpre um papel dentro da cadeia." },
          { id: "c", text: "Apenas a etapa de recaptação, que é opcional." },
        ],
        correctAnswer: "b",
        explanation: "Anti-personificação: transmissor age ligado a receptor, dentro de circuito e contexto.",
        hint1: "O que faz a molécula fazer algo?",
        hint2: "Receptor + circuito.",
        hint3: "Efeito emerge da cadeia, não da molécula solta.",
        errorKind: "language",
      },
    ],
    summary: {
      shouldKnow: [
        "Reconstruir a cadeia até o receptor.",
        "Isolar o Ca²⁺ como acoplamento da liberação.",
        "Recusar a personificação do transmissor.",
      ],
      acquiredConcepts: [
        "synapse",
        "calcium_channels",
        "vesicles",
        "neurotransmitter",
        "synaptic_cleft",
        "receptor",
      ],
    },
    masteryCriteria: mastery,
    references: [
      { title: "Südhof, neurotransmitter release", kind: "revisao" },
      { title: "Kandel et al.", kind: "livro" },
    ],
    contentVersion: "1.0",
  },
  {
    id: "module_07",
    stage: 1,
    number: 7,
    title: "Receptores e efeitos sinápticos",
    shortTitle: "Receptores",
    objective:
      "Distinguir ionotrópicos e metabotrópicos, excitação, inibição, modulação, recaptação e degradação — sempre pelo receptor, não pelo nome da molécula.",
    centralQuestion: "O que o ligante faz depois de chegar — e quem decide o efeito?",
    prerequisites: ["module_06"],
    estimatedTime: { essential: 9, deepen: 7, questions: 5 },
    concepts: [
      "receptor",
      "ionotropic",
      "metabotropic",
      "excitation",
      "inhibition",
      "modulation",
      "reuptake",
    ],
    introduction:
      "A fenda já tem transmissor. Se pararmos aqui, a tentação é nomear a molécula como se ela fosse o efeito. Este módulo desloca o centro para o receptor e para o destino do ligante.",
    blocks: [
      {
        id: "m07-q",
        kind: "question",
        body: "Por que a mesma molécula pode excitar uma célula e inibir outra?",
      },
      {
        id: "m07-a",
        kind: "answer",
        body: "Porque o [[receptor|receptor]] — e o íon ou a cascata que ele aciona — define o efeito. O nome do transmissor não basta.",
        conceptIds: ["receptor"],
      },
      {
        id: "m07-ion",
        kind: "explain",
        title: "Dois grandes modos",
        body: "[[ionotropic|Ionotrópico]]: canal gated por ligante, efeito relativamente rápido no potencial. [[metabotropic|Metabotrópico]]: vias intracelulares, frequentemente mais lentas e amplas, centrais à [[modulation|modulação]].",
        conceptIds: ["ionotropic", "metabotropic", "modulation"],
      },
      {
        id: "m07-ei",
        kind: "explain",
        title: "Excitação e inibição são relativas",
        body: "[[excitation|Excitação]] aproxima do limiar; [[inhibition|inibição]] reduz a probabilidade de disparo (por potencial ou por condutância). Nenhuma das duas é um comportamento. Inibição é cálculo, não 'desligar o cérebro'.",
        conceptIds: ["excitation", "inhibition"],
      },
      {
        id: "m07-end",
        kind: "mechanism",
        title: "Como o sinal termina",
        steps: [
          { id: "r", title: "Recaptação", body: "Transportadores na pré-sináptica ou na glia." },
          { id: "d", title: "Degradação", body: "Enzimas na fenda ou na célula." },
          { id: "f", title: "Difusão", body: "O ligante se vai. A geometria importa." },
        ],
        conceptIds: ["reuptake"],
      },
      {
        id: "m07-recall",
        kind: "recall",
        body: "Complete: o efeito de um transmissor não está escrito no nome da molécula, está escrito no…",
      },
      {
        id: "m07-pharm",
        kind: "explain",
        title: "Fármacos mudam temporalidade",
        body: "Bloquear recaptação não 'cria felicidade'. Muda quanto tempo o ligante permanece disponível. O efeito clínico, quando existe, atravessa circuitos, tempo e contexto — e não autoriza diagnóstico por este app.",
        layer: 2,
      },
    ],
    misconceptions: [
      {
        claim: "O transmissor determina o efeito; o receptor é detalhe.",
        whyPlausible: "Falamos 'gabaérgico' e 'glutamatérgico' como se o nome bastasse.",
        problem: "Há receptores com ações distintas para o mesmo ligante. A abreviação didática vira erro se for ontologizada.",
        better: "Pergunte sempre: qual receptor, em qual célula, em qual circuito.",
      },
    ],
    integration:
      "Com receptores, o neurônio pode ser excitado, inibido ou modulado. O módulo 8 pergunta como isso vira um circuito.",
    relatedModules: ["module_06", "module_08", "module_14"],
    questions: [
      {
        id: "m07-q1",
        moduleId: "module_07",
        conceptIds: ["receptor"],
        type: "recognition",
        difficulty: 1,
        prompt: "O efeito imediato de um neurotransmissor depende principalmente:",
        options: [
          { id: "a", text: "Do nome popular da molécula ('felicidade', 'medo')." },
          { id: "b", text: "Do receptor e do contexto celular em que ele está." },
          { id: "c", text: "Do hemisfério cerebral em que a pessoa 'é mais forte'." },
        ],
        correctAnswer: "b",
        explanation: "Regra de ouro da etapa 1, que a etapa 2 vai reutilizar na dopamina.",
        hint1: "A mesma molécula, dois efeitos.",
        hint2: "Quem transduz a ligação?",
        hint3: "Receptor.",
      },
      {
        id: "m07-q2",
        moduleId: "module_07",
        conceptIds: ["metabotropic"],
        type: "relation",
        difficulty: 2,
        prompt: "Receptores metabotrópicos são especialmente importantes para:",
        options: [
          { id: "a", text: "Apenas o potencial de ação no nódulo de Ranvier." },
          { id: "b", text: "Modulação de estado, ganho e, frequentemente, efeitos mais lentos." },
          { id: "c", text: "Substituir a mielina." },
        ],
        correctAnswer: "b",
        explanation: "Não são um luxo avançado. São parte do cálculo de circuitos reais.",
        hint1: "Pense em segundos a minutos, não só em 1 ms.",
        hint2: "Cascata, não necessariamente poro imediato.",
        hint3: "Modulação.",
      },
      {
        id: "m07-q3",
        moduleId: "module_07",
        conceptIds: ["inhibition"],
        type: "misconception",
        difficulty: 2,
        prompt: "Inibição sináptica significa:",
        options: [
          { id: "a", text: "O cérebro desliga." },
          { id: "b", text: "Uma influência que reduz a probabilidade de disparo da célula-alvo — componente ativo do cálculo neural." },
          { id: "c", text: "A pessoa ficou triste." },
        ],
        correctAnswer: "b",
        explanation: "Erro de escala clássico: inibição celular ≠ estado psicológico.",
        hint1: "É sobre a célula-alvo.",
        hint2: "Pode ser hiperpolarização ou shunt.",
        hint3: "Cálculo, não humor.",
        errorKind: "scale",
      },
      {
        id: "m07-q4",
        moduleId: "module_07",
        conceptIds: ["reuptake"],
        type: "application",
        difficulty: 2,
        prompt:
          "Um fármaco bloqueia a recaptação de um transmissor. Qual descrição é mais cuidadosa?",
        options: [
          { id: "a", text: "O fármaco fabrica a emoção correspondente à molécula." },
          { id: "b", text: "O fármaco altera a temporalidade e a disponibilidade do ligante na fenda; o efeito depende de circuitos e contexto." },
          { id: "c", text: "O fármaco prova que a pessoa tinha falta daquela molécula como causa única." },
        ],
        correctAnswer: "b",
        explanation: "Mecanismo local ≠ etiologia de um transtorno. Este app não diagnostica.",
        hint1: "O que a recaptação faz no tempo do sinal?",
        hint2: "Disponibilidade na fenda.",
        hint3: "Não salte para a biografia da pessoa.",
        errorKind: "causal",
      },
      {
        id: "m07-q5",
        moduleId: "module_07",
        conceptIds: ["receptor", "modulation"],
        type: "recall",
        difficulty: 1,
        prompt: "Em uma frase, explique por que o mesmo transmissor pode produzir efeitos opostos em regiões diferentes.",
        correctAnswer: "open",
        modelAnswer:
          "Porque o efeito depende do tipo de receptor pós-sináptico e do circuito em que a sinapse está inserida, não da molécula por si só.",
        explanation: "Fecha o argumento anti-personificação: molécula é insumo; receptor + circuito determinam o efeito.",
        hint1: "Quem lê a mensagem?",
        hint2: "Contexto de circuito.",
        hint3: "Molécula ≠ significado.",
      },
    ],
    summary: {
      shouldKnow: [
        "Deixar o receptor no centro do efeito.",
        "Distinguir ionotrópico e metabotrópico.",
        "Tratar inibição como cálculo e recaptação como temporalidade.",
      ],
      acquiredConcepts: [
        "receptor",
        "ionotropic",
        "metabotropic",
        "excitation",
        "inhibition",
        "modulation",
        "reuptake",
      ],
    },
    masteryCriteria: mastery,
    references: [
      { title: "Purves et al., Neuroscience", kind: "livro" },
      { title: "Nestler, Hyman & Malenka, Molecular Neuropharmacology", kind: "livro" },
    ],
    contentVersion: "1.0",
  },
  {
    id: "module_08",
    stage: 1,
    number: 8,
    title: "Do neurônio ao circuito",
    shortTitle: "Integração",
    objective:
      "Mostrar como alterações microscópicas na membrana contribuem para a comunicação entre circuitos — fechando a etapa 1 sem saltar para o comportamento.",
    centralQuestion:
      "Como alterações microscópicas na membrana de um neurônio podem contribuir para a comunicação entre circuitos?",
    prerequisites: ["module_06", "module_07"],
    estimatedTime: { essential: 8, deepen: 6, questions: 5 },
    concepts: ["integration", "circuit"],
    introduction:
      "Você tem peças: gradiente, spike, sinapse, receptor. Este módulo não acrescenta um transmissor novo. Integra. O neurônio soma. O circuito opera. O comportamento ainda não foi explicado — e essa recusa é o ponto.",
    blocks: [
      {
        id: "m08-q",
        kind: "question",
        body: "Uma sinapse isolada 'decide' o comportamento?",
      },
      {
        id: "m08-a",
        kind: "answer",
        body: "Não. O neurônio faz [[integration|integração]] espacial e temporal de muitas entradas. Um [[circuit|circuito]] é a dinâmica de muitos neurônios. Comportamento é ainda outro nível.",
        conceptIds: ["integration", "circuit"],
      },
      {
        id: "m08-chain",
        kind: "mechanism",
        title: "A cadeia que você deve reconstruir",
        steps: [
          { id: "1", title: "Gradientes iônicos", body: "Energia potencial química." },
          { id: "2", title: "Potencial de membrana", body: "Compromisso de permeabilidades." },
          { id: "3", title: "Limiar e canais", body: "Na⁺ e K⁺ voltage-gated." },
          { id: "4", title: "Propagação", body: "Regeneração, mielina, nódulos." },
          { id: "5", title: "Terminal e Ca²⁺", body: "Acoplamento à exocitose." },
          { id: "6", title: "Receptor", body: "Efeito na célula seguinte." },
          { id: "7", title: "Integração e circuito", body: "Muitas células, uma operação." },
        ],
      },
      {
        id: "m08-limit",
        kind: "limit",
        title: "O que esta etapa não concluiu",
        body: "Não concluímos o que é uma emoção, um hábito ou uma decisão. Concluímos o chão sobre o qual essas descrições podem ser construídas sem virar mágica.",
      },
      {
        id: "m08-recall",
        kind: "recall",
        body: "Recite a cadeia da etapa 1 em voz alta. Onde você trava? Esse ponto volta na revisão.",
      },
    ],
    misconceptions: [
      {
        claim: "Já entendemos o comportamento, porque entendemos o neurônio.",
        whyPlausible: "A tentação reducionista: o menor nível parece o mais 'científico'.",
        problem: "É um erro de escala. O neurônio é necessário ao modelo, não suficiente para o fenômeno social.",
        better: "Levamos os mecanismos adiante como fundamento, não como substituto.",
      },
    ],
    integration:
      "A etapa 2 começa no circuito e recusa a ideia de que emoção é uma área. Os mecanismos celulares continuam valendo.",
    relatedModules: ["module_01", "module_09", "module_16"],
    questions: [
      {
        id: "m08-q1",
        moduleId: "module_08",
        conceptIds: ["integration"],
        type: "recognition",
        difficulty: 1,
        prompt: "Integração neuronal é:",
        options: [
          { id: "a", text: "Cada sinapse dispara sozinha o comportamento." },
          { id: "b", text: "A soma espacial e temporal de influências que molda o padrão de disparo." },
          { id: "c", text: "A união dos hemisférios pela força de vontade." },
        ],
        correctAnswer: "b",
        explanation: "O neurônio é integrador, não relé de uma única entrada.",
        hint1: "Muitas entradas, uma decisão de disparo.",
        hint2: "Espaço e tempo.",
        hint3: "Soma, não relé.",
      },
      {
        id: "m08-q2",
        moduleId: "module_08",
        conceptIds: ["circuit", "levels_of_analysis"],
        type: "limit",
        difficulty: 2,
        prompt: "Compreender a membrana de um neurônio autoriza explicar um hábito social?",
        options: [
          { id: "a", text: "Sim, porque tudo é sódio." },
          { id: "b", text: "Não automaticamente. Há níveis intermediários (circuito, sistema, cognição, contexto) que não podem ser saltados." },
        ],
        correctAnswer: "b",
        explanation: "Fecho da etapa 1. A etapa 4 vai repetir isso na intervenção.",
        hint1: "Volte ao módulo 1.",
        hint2: "Participação versus suficiência, agora entre níveis.",
        hint3: "Não pule a escada.",
        errorKind: "scale",
      },
      {
        id: "m08-q3",
        moduleId: "module_08",
        conceptIds: ["circuit"],
        type: "integration",
        difficulty: 2,
        prompt:
          "Relacione: alteração de permeabilidade na membrana → ? → comunicação entre células → ?",
        options: [
          { id: "a", text: "Potencial de ação / influência sináptica em um circuito" },
          { id: "b", text: "Felicidade / destreza" },
          { id: "c", text: "Hemisfério direito / hemisfério esquerdo" },
        ],
        correctAnswer: "a",
        explanation: "A cadeia conceitual, não a cadeia de slogans.",
        hint1: "Use só o vocabulário da etapa 1.",
        hint2: "Spike, depois sinapse.",
        hint3: "Circuito no fim.",
      },
      {
        id: "m08-q4",
        moduleId: "module_08",
        conceptIds: ["integration"],
        type: "recall",
        difficulty: 2,
        prompt: "Reconstrua, em uma cadeia, o caminho do gradiente iônico até o circuito.",
        correctAnswer: "open",
        modelAnswer:
          "Gradiente → potencial de membrana → limiar → potencial de ação → propagação → Ca²⁺ no terminal → transmissor → receptor → integração → circuito.",
        explanation: "Se faltar o Ca²⁺ ou o receptor, a cadeia está furada. Se aparecer 'medo' no meio, houve salto.",
        hint1: "Comece no íon, termine no conjunto de células.",
        hint2: "Não pule a sinapse.",
        hint3: "Ca²⁺ está no meio.",
      },
      {
        id: "m08-q5",
        moduleId: "module_08",
        conceptIds: ["integration", "circuit"],
        type: "counterfactual",
        difficulty: 2,
        prompt:
          "Se cada neurônio de um circuito funcionasse isoladamente (mesmas propriedades, sem trocar sinais), o que a integração perderia?",
        options: [
          { id: "a", text: "Nada; a soma dos neurônios já dá o comportamento do circuito." },
          { id: "b", text: "Perderia a computação distribuída — padrões, seleção e regulação surgem da interação, não da soma isolada." },
          { id: "c", text: "Ganharia velocidade porque não haveria atrasos sinápticos." },
        ],
        correctAnswer: "b",
        explanation: "Fecha a etapa 1: circuito ≠ soma; o próximo estágio explora essa emergência.",
        hint1: "Interação vs. soma.",
        hint2: "Emergência aparece só quando há troca.",
        hint3: "Padrão coletivo.",
        errorKind: "causal",
      },
    ],
    summary: {
      shouldKnow: [
        "Recitar a cadeia da etapa 1.",
        "Definir integração e circuito.",
        "Recusar o salto ao comportamento.",
      ],
      acquiredConcepts: ["integration", "circuit"],
    },
    masteryCriteria: mastery,
    references: [
      { title: "Shepherd, The Synaptic Organization of the Brain", kind: "livro" },
      { title: "Craver, Explaining the Brain", kind: "livro" },
    ],
    contentVersion: "1.0",
  },
];
