import type { ModuleContent, Question } from "../types.ts";

const mastery = { comprehension: 70, recall: 70, contrast: 70, application: 60 };
const refs = [
  { title: "Baddeley, Eysenck & Anderson, Memory", kind: "livro" as const },
  { title: "Kahneman, Thinking, Fast and Slow", kind: "livro" as const, note: "modelo didático; não ontologizar" },
  { title: "Gazzaniga, Ivry & Mangun, Cognitive Neuroscience", kind: "livro" as const },
];
function q(p: Question): Question {
  return p;
}

export const STAGE_3_MODULES: ModuleContent[] = [
  {
    id: "module_17",
    stage: 3,
    number: 17,
    title: "Atenção",
    shortTitle: "Atenção",
    objective: "Tratar atenção como família de processos seletivos, não como holofote único nem como tanque de combustível.",
    centralQuestion: "O que está sendo selecionado — e às custas de quê?",
    prerequisites: ["module_16"],
    estimatedTime: { essential: 8, deepen: 6, questions: 4 },
    concepts: ["attention"],
    introduction:
      "A etapa 3 descreve fenômenos cognitivos como outro nível, não como substituto da biologia. Atenção é o primeiro: seleção, não magia.",
    blocks: [
      { id: "m17-q", kind: "question", body: "Atenção é um holofote no lobo parietal?" },
      { id: "m17-a", kind: "answer", body: "Não. [[attention|Atenção]] reúne processos de alerta, orientação e controle que selecionam informação e alocam recursos limitados. Redes distintas, metas distintas." },
      { id: "m17-e", kind: "explain", title: "Limitação sem mistério", body: "Não processamos tudo com a mesma fidelidade. Isso não prova um tanque único. Interferência, predição e saliência mudam o que entra." },
      { id: "m17-r", kind: "recall", body: "Nomeie dois processos atencionais que não são a mesma coisa (por exemplo alerta versus seleção)." },
      { id: "m17-l", kind: "limit", title: "Não diagnostique", body: "Dificuldade atencional cotidiana não autoriza um rótulo clínico neste app.", layer: 1 },
    ],
    misconceptions: [{ claim: "Atenção é um músculo único no córtex.", whyPlausible: "Falamos 'presta atenção' no singular.", problem: "Família de sistemas; lesões dissociam componentes.", better: "Alerta, orientação, controle — no mínimo uma tríade útil." }],
    integration: "A memória de trabalho vai herdar essa limitação.",
    relatedModules: ["module_18", "module_21", "module_29"],
    questions: [
      q({ id: "m17-q1", moduleId: "module_17", conceptIds: ["attention"], type: "misconception", difficulty: 1, prompt: "Atenção é melhor descrita como:", options: [{ id: "a", text: "Um holofote único localizado numa área." }, { id: "b", text: "Família de processos que selecionam informação e alocam recursos." }], correctAnswer: "b", explanation: "Pluralidade.", hint1: "Mais de um sistema.", hint2: "Seleção.", hint3: "Não um lugar.", errorKind: "scale" }),
      q({ id: "m17-q2", moduleId: "module_17", conceptIds: ["attention"], type: "application", difficulty: 2, prompt: "Alguém não ouve o nome numa festa barulhenta. A análise mais útil:", options: [{ id: "a", text: "Diagnóstico imediato." }, { id: "b", text: "Seleção em ambiente de competição; carga, predição e meta importam — sem fechar um laudo." }], correctAnswer: "b", explanation: "Aplicação + limite.", hint1: "Competição.", hint2: "Não laude.", hint3: "Contexto.", errorKind: "generalization" }),
      q({ id: "m17-q3", moduleId: "module_17", conceptIds: ["attention"], type: "recall", difficulty: 1, prompt: "Por que atenção não substitui a biologia da etapa 1?", correctAnswer: "open", modelAnswer: "Porque seleção é descrição cognitiva de operações que ainda acontecem em circuitos, com neuromodulação e restrições celulares. É outro nível, não outro mundo.", explanation: "Níveis.", hint1: "Outro nível.", hint2: "Circuitos ainda existem.", hint3: "Não substitui." }),
      q({ id: "m17-q4", moduleId: "module_17", conceptIds: ["attention"], type: "limit", difficulty: 2, prompt: "Falhar numa tarefa de atenção prova ausência de uma área?", options: [{ id: "a", text: "Sim, sempre." }, { id: "b", text: "Não. Tarefas são compostas; sono, meta, ruído e estratégia também pesam." }], correctAnswer: "b", explanation: "Tarefa ≠ faculdade isolada.", hint1: "Composição.", hint2: "Estado.", hint3: "Não isole.", errorKind: "causal" }),
      q({ id: "m17-q5", moduleId: "module_17", conceptIds: ["attention"], type: "counterfactual", difficulty: 2, prompt: "Se o subsistema de controle atencional (executivo) falhasse seletivamente, o que ainda funcionaria?", options: [{ id: "a", text: "Nada: sem controle, nenhuma seleção ocorre." }, { id: "b", text: "Alerta e orientação a estímulos salientes tendem a se preservar; o custo aparece em priorização por meta e resistência à interferência." }], correctAnswer: "b", explanation: "Componentes dissociáveis.", hint1: "Alerta.", hint2: "Orientação.", hint3: "Meta é o que cai.", errorKind: "causal" }),
    ],
    summary: { shouldKnow: ["Falar de atenção no plural.", "Não diagnosticar a partir de um lapso."], acquiredConcepts: ["attention"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_18",
    stage: 3,
    number: 18,
    title: "Memória",
    shortTitle: "Memória",
    objective: "Separar memória de trabalho, encoding, recuperação e sistemas de longo prazo — com reconstrução no centro.",
    centralQuestion: "Lembrar é copiar ou reconstruir?",
    prerequisites: ["module_17"],
    estimatedTime: { essential: 9, deepen: 6, questions: 5 },
    concepts: ["working_memory", "encoding", "retrieval", "long_term_memory"],
    introduction: "A etapa 2 mostrou modulação afetiva. Agora a arquitetura: não há um armazém único, e recuperar é um evento novo. Por isso este app testa em vez de só exibir.",
    blocks: [
      { id: "m18-q", kind: "question", body: "Por que reler não é o mesmo que conseguir explicar?" },
      { id: "m18-a", kind: "answer", body: "Porque [[encoding|codificar]] não copia o mundo, e [[retrieval|recuperar]] reconstrói com pistas. Reconhecer um texto não prova que você reconstrói o mecanismo." },
      { id: "m18-m", kind: "mechanism", title: "Famílias", steps: [
        { id: "w", title: "Trabalho", body: "[[working_memory|Manter e manipular]] com capacidade limitada, em diálogo com atenção." },
        { id: "e", title: "Episódica / semântica / procedimental", body: "[[long_term_memory|Sistemas]] distintos, com dissociações clínicas." },
        { id: "r", title: "Recuperação", body: "Evento novo. Pode fortalecer ou distorcer." },
      ]},
      { id: "m18-r", kind: "recall", body: "Sem olhar: por que este aplicativo insiste em recuperação ativa?" },
      { id: "m18-l", kind: "explain", title: "O número 7", body: "O '7±2' é histórico e contextual. Não transforme em QI nem em lei universal de itens.", layer: 2 },
    ],
    misconceptions: [{ claim: "Memória é um arquivo intacto num único lugar.", whyPlausible: "Metáfora do computador.", problem: "Sistemas múltiplos + reconstrução.", better: "Família de sistemas; lembrar é um ato." }],
    integration: "Plasticidade vai dizer como a experiência deixa traço — com limites.",
    relatedModules: ["module_15", "module_19", "module_01"],
    questions: [
      q({ id: "m18-q1", moduleId: "module_18", conceptIds: ["retrieval"], type: "misconception", difficulty: 1, prompt: "Lembrar é:", options: [{ id: "a", text: "Ler um arquivo intacto." }, { id: "b", text: "Reconstruir a partir de pistas, estado e conhecimento atual." }], correctAnswer: "b", explanation: "Núcleo pedagógico do app.", hint1: "Evento novo.", hint2: "Pistas.", hint3: "Reconstrução.", errorKind: "generalization" }),
      q({ id: "m18-q2", moduleId: "module_18", conceptIds: ["working_memory"], type: "application", difficulty: 2, prompt: "Instruções longas falham no meio do ruído. Mecanismo mais pertinente:", options: [{ id: "a", text: "Falta de caráter." }, { id: "b", text: "Capacidade limitada de manter e manipular, em competição atencional." }], correctAnswer: "b", explanation: "Carga, não moral.", hint1: "Limite.", hint2: "Atenção.", hint3: "Não moralize.", errorKind: "scale" }),
      q({ id: "m18-q3", moduleId: "module_18", conceptIds: ["long_term_memory"], type: "relation", difficulty: 2, prompt: "Dissociações clínicas (perder episódios e preservar procedimentos) sugerem:", options: [{ id: "a", text: "Um único armazém com dois rótulos." }, { id: "b", text: "Sistemas parcialmente separáveis." }], correctAnswer: "b", explanation: "Argumento clássico de múltiplos sistemas.", hint1: "Saber como versus lembrar quando.", hint2: "Separáveis.", hint3: "Não um HD." }),
      q({ id: "m18-q4", moduleId: "module_18", conceptIds: ["encoding"], type: "recall", difficulty: 1, prompt: "O que a codificação faz que a mera exposição não garante?", correctAnswer: "open", modelAnswer: "Constrói uma representação influenciada por atenção e conhecimento prévio, potencialmente recuperável — exposição passiva pode não criar essa representacão utilizável.", explanation: "Por isso blocos curtos + pergunta.", hint1: "Construção.", hint2: "Atenção.", hint3: "Não cópia." }),
      q({ id: "m18-q5", moduleId: "module_18", conceptIds: ["retrieval"], type: "limit", difficulty: 2, prompt: "Uma lembrança vívida de um conteúdo estudado prova domínio do mecanismo?", options: [{ id: "a", text: "Sim, familiaridade é domínio." }, { id: "b", text: "Não. Familiaridade pode ser reconhecimento sem reconstrução." }], correctAnswer: "b", explanation: "exposição ≠ domínio.", hint1: "Princípio do produto.", hint2: "Reconhecer versus explicar.", hint3: "Não prova.", errorKind: "causal" }),
    ],
    summary: { shouldKnow: ["Separar sistemas.", "Defender recuperação ativa.", "Recusar o arquivo."], acquiredConcepts: ["working_memory", "encoding", "retrieval", "long_term_memory"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_19",
    stage: 3,
    number: 19,
    title: "Aprendizagem e plasticidade",
    shortTitle: "Plasticidade",
    objective: "Ligar aprendizagem a plasticidade sem vender neuroplasticidade ilimitada.",
    centralQuestion: "O que muda com a experiência — e o que não é milagre?",
    prerequisites: ["module_18", "module_06"],
    estimatedTime: { essential: 8, deepen: 6, questions: 4 },
    concepts: ["plasticity", "learning"],
    introduction: "Sinapses mudam. Isso é verdadeiro e foi transformado em slogan. Aqui devolvemos o termo ao chão: restrições, custos, múltiplas formas de aprender.",
    blocks: [
      { id: "m19-q", kind: "question", body: "'O cérebro muda' autoriza qualquer método?" },
      { id: "m19-a", kind: "answer", body: "Não. [[plasticity|Plasticidade]] é capacidade real e limitada. [[learning|Aprendizagem]] tem formas associativas, estatísticas, procedimentais, sociais — não um único LTP mágico." },
      { id: "m19-e", kind: "explain", title: "Dois cuidados", body: "1) Plasticidade pode ser desadaptativa. 2) Mudança sináptica não é o único nível (excitabilidade, glia, rede). O essencial: experiência deixa traço sob restrições." },
      { id: "m19-r", kind: "recall", body: "Cite uma restrição da plasticidade (janela, custo, ou especificidade)." },
      { id: "m19-l", kind: "limit", title: "Marketing", body: "Produtos que vendem 'reprograme seu cérebro em 7 dias' usam um fato verdadeiro como cheque em branco.", layer: 1 },
    ],
    misconceptions: [{ claim: "Neuroplasticidade é ilimitada.", whyPlausible: "Histórias de recuperação são reais e comoventes.", problem: "Anedota ≠ ausência de teto biológico e social.", better: "Capacidade restrita, dependente de dose, tempo e contexto." }],
    integration: "Decisão e hábito vão usar aprendizagem com políticas de ação diferentes.",
    relatedModules: ["module_14", "module_22"],
    questions: [
      q({ id: "m19-q1", moduleId: "module_19", conceptIds: ["plasticity"], type: "misconception", difficulty: 1, prompt: "Plasticidade:", options: [{ id: "a", text: "É um superpoder irrestrito." }, { id: "b", text: "É capacidade real de mudança, com restrições, custos e possíveis efeitos desadaptativos." }], correctAnswer: "b", explanation: "Anti-milagre.", hint1: "Restrição.", hint2: "Custo.", hint3: "Não ilimitada.", errorKind: "generalization" }),
      q({ id: "m19-q2", moduleId: "module_19", conceptIds: ["learning"], type: "relation", difficulty: 2, prompt: "Aprendizagem se reduz a um único mecanismo celular?", options: [{ id: "a", text: "Sim, LTP explica tudo." }, { id: "b", text: "Não. Há múltiplas formas e níveis; LTP é um mecanismo estudado, não o dicionário da vida mental." }], correctAnswer: "b", explanation: "Erro de escala outra vez.", hint1: "Múltiplas formas.", hint2: "Nível celular ≠ fenômeno.", hint3: "Não reduza.", errorKind: "scale" }),
      q({ id: "m19-q3", moduleId: "module_19", conceptIds: ["learning"], type: "recall", difficulty: 1, prompt: "Por que recuperação e contraste, neste app, são aprendizagem e não só medição?", correctAnswer: "open", modelAnswer: "Porque recuperar e diferenciar fortalecem e reorganizam representações; o teste é um evento de encoding/retrieval, não apenas uma nota.", explanation: "Pedagogia baseada no módulo 18–19.", hint1: "Teste como evento.", hint2: "Reconstrução.", hint3: "Não só nota." }),
      q({ id: "m19-q4", moduleId: "module_19", conceptIds: ["plasticity"], type: "application", difficulty: 2, prompt: "Um curso promete 'ativar plasticidade' com um exercício de 3 minutos. Sua pergunta:", options: [{ id: "a", text: "Qual mudança, em qual sistema, com qual evidência — e o que não se pode concluir?" }, { id: "b", text: "Nada: plasticidade é sempre boa e imediata." }], correctAnswer: "a", explanation: "Checklist científico.", hint1: "Qual sistema.", hint2: "Evidência.", hint3: "Limite.", errorKind: "generalization" }),
      q({ id: "m19-q5", moduleId: "module_19", conceptIds: ["plasticity"], type: "limit", difficulty: 2, prompt: "Plasticidade pode ser desadaptativa?", options: [{ id: "a", text: "Não: mudar é sempre bom." }, { id: "b", text: "Sim: rearranjos após lesão ou uso repetitivo podem consolidar padrões prejudiciais; mudança é neutra até que se avalie custo e função." }], correctAnswer: "b", explanation: "Anti-slogan.", hint1: "Dor crônica.", hint2: "Padrões travados.", hint3: "Mudar ≠ melhorar.", errorKind: "generalization" }),
    ],
    summary: { shouldKnow: ["Definir plasticidade com teto.", "Pluralizar aprendizagem."], acquiredConcepts: ["plasticity", "learning"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_20",
    stage: 3,
    number: 20,
    title: "Tomada de decisão",
    shortTitle: "Decisão",
    objective: "Descrever decisão como integração de valor, incerteza e custo em mais de um sistema — sem cérebro racional versus emocional.",
    centralQuestion: "Quem decide — e por que essa pergunta já começa mal?",
    prerequisites: ["module_18", "module_14"],
    estimatedTime: { essential: 8, deepen: 6, questions: 4 },
    concepts: ["decision_making"],
    introduction: "Não há um homúnculo no córtex frontal. Há políticas de ação em competição, com tempo, incerteza e normas.",
    blocks: [
      { id: "m20-q", kind: "question", body: "O córtex decide e a amígdala atrapalha?" },
      { id: "m20-a", kind: "answer", body: "Essa história é um neuromito útil para filmes. [[decision_making|Decidir]] integra evidência, valor, esforço e normas em sistemas que incluem, entre outros, circuitos cortico-estriatais e neuromodulação." },
      { id: "m20-e", kind: "explain", title: "Múltiplos controladores", body: "Modelos distinguem, por exemplo, controle deliberativo (sensível a metas e modelos) e habitual (sensível a pistas). Não é razão versus emoção como essências." },
      { id: "m20-r", kind: "recall", body: "Substitua 'o cérebro racional perdeu para o emocional' por uma frase com sistemas de controle." },
    ],
    misconceptions: [{ claim: "Hemisfério esquerdo decide, direito sente.", whyPlausible: "Assimetrias reais viram personalidade.", problem: "Erro de escala e de evidência.", better: "Redes bilaterais; a dicotomia não explica a escolha." }],
    integration: "O próximo módulo oferece um modelo didático de rápido/lento — marcado como modelo.",
    relatedModules: ["module_21", "module_22", "module_14"],
    questions: [
      q({ id: "m20-q1", moduleId: "module_20", conceptIds: ["decision_making"], type: "misconception", difficulty: 1, prompt: "Qual formulação é melhor?", options: [{ id: "a", text: "O córtex racional luta contra o cérebro emocional." }, { id: "b", text: "Sistemas de controle com sensibilidades diferentes (meta, pista, valor, tempo) competem e cooperam." }], correctAnswer: "b", explanation: "Anti-dualismo neural.", hint1: "Sistemas.", hint2: "Não essências.", hint3: "Competem e cooperam.", errorKind: "scale" }),
      q({ id: "m20-q2", moduleId: "module_20", conceptIds: ["decision_making"], type: "application", difficulty: 2, prompt: "Uma escolha ruim sob pressa. Análise mais pertinente:", options: [{ id: "a", text: "A pessoa é irracional por natureza." }, { id: "b", text: "Tempo, incerteza e custo mudam qual controlador prevalece; o erro pode ser previsível sem ser um veredito de caráter." }], correctAnswer: "b", explanation: "Mecanismo, não moral.", hint1: "Tempo.", hint2: "Controladores.", hint3: "Não caráter.", errorKind: "generalization" }),
      q({ id: "m20-q3", moduleId: "module_20", conceptIds: ["decision_making"], type: "recall", difficulty: 1, prompt: "Por que 'quem decide?' é uma pergunta mal feita?", correctAnswer: "open", modelAnswer: "Porque sugere um único decisor. A descrição melhor é de processos e políticas de ação distribuídos no tempo.", explanation: "Homúnculo.", hint1: "Homúnculo.", hint2: "Distribuído.", hint3: "Processos." }),
      q({ id: "m20-q4", moduleId: "module_20", conceptIds: ["dopamine"], type: "relation", difficulty: 2, prompt: "A dopamina entra na decisão principalmente como:", options: [{ id: "a", text: "A essência do prazer da escolha." }, { id: "b", text: "Neuromodulação de aprendizagem e de vigor/valor em circuitos — dependente de via e contexto." }], correctAnswer: "b", explanation: "Transferência do módulo 14.", hint1: "Módulo 14.", hint2: "Não prazer.", hint3: "Modulação.", errorKind: "language" }),
      q({ id: "m20-q5", moduleId: "module_20", conceptIds: ["decision_making"], type: "counterfactual", difficulty: 2, prompt: "Se o tempo disponível para escolher caísse a milissegundos, o que se espera dos controladores?", options: [{ id: "a", text: "O deliberativo, que exige simulação, tende a perder peso; políticas mais automáticas e cache de valor tendem a decidir." }, { id: "b", text: "Nada muda: decisão é uma função única." }], correctAnswer: "a", explanation: "Temporalidade recruta controladores.", hint1: "Tempo.", hint2: "Deliberação custa.", hint3: "Automatismo entra.", errorKind: "causal" }),
    ],
    summary: { shouldKnow: ["Recusar o duelo razão/emoção.", "Falar de controladores e restrições."], acquiredConcepts: ["decision_making"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_21",
    stage: 3,
    number: 21,
    title: "Processamento rápido e lento",
    shortTitle: "Rápido e lento",
    objective: "Usar a distinção rápido/lento como heurística didática, abandonando o cérebro triuno.",
    centralQuestion: "Quando o modelo de dois sistemas ajuda — e quando vira anatomia falsa?",
    prerequisites: ["module_20"],
    estimatedTime: { essential: 7, deepen: 5, questions: 4 },
    concepts: ["dual_process"],
    introduction: "Modelos de dois processos são úteis para ensinar vieses e hábitos. Tornam-se lixo quando viram réptil versus humano.",
    blocks: [
      { id: "m21-q", kind: "question", body: "Temos um cérebro reptiliano que sabota o racional?" },
      { id: "m21-a", kind: "answer", body: "Não. [[dual_process|Rápido e lento]] é uma família de modelos cognitivos. Não é um empilhamento evolutivo de três cérebros." },
      { id: "m21-e", kind: "explain", title: "Como usar o modelo", body: "Rápido: mais automático, menor custo consciente. Lento: mais controlado, mais custoso. Ambos erram e ambos acertam. Marque: é um modelo." },
      { id: "m21-r", kind: "recall", body: "Diga em voz alta: 'isto é um modelo, não um mapa do encéfalo'." },
    ],
    misconceptions: [{ claim: "Cérebro triuno: réptil, mamífero, racional.", whyPlausible: "Didática antiga e livros populares.", problem: "Evolução não empilha cérebros prontos; o modelo hierarquiza emoção como inferior.", better: "Sistemas integrados; rápido/lento como descrição, não como anatomia." }],
    integration: "Hábitos são um caso em que o controle rápido (em relação à meta atual) é exatamente o esperado.",
    relatedModules: ["module_22", "module_23"],
    questions: [
      q({ id: "m21-q1", moduleId: "module_21", conceptIds: ["dual_process"], type: "misconception", difficulty: 1, prompt: "O cérebro triuno:", options: [{ id: "a", text: "É a anatomia oficial." }, { id: "b", text: "É um modelo didático ultrapassado e enganoso se ontologizado." }], correctAnswer: "b", explanation: "Neuromito nomeado no manuscrito.", hint1: "Empilhamento falso.", hint2: "Não ontologize.", hint3: "Ultrapassado.", errorKind: "factual" }),
      q({ id: "m21-q2", moduleId: "module_21", conceptIds: ["dual_process"], type: "limit", difficulty: 2, prompt: "Quando o modelo rápido/lento deixa de funcionar bem?", options: [{ id: "a", text: "Quando vira dois cérebros e moraliza o rápido como inferior." }, { id: "b", text: "Nunca: é a verdade literal." }], correctAnswer: "a", explanation: "Pergunta de limite do modelo.", hint1: "Ontologizar.", hint2: "Moralizar.", hint3: "Dois cérebros.", errorKind: "language" }),
      q({ id: "m21-q3", moduleId: "module_21", conceptIds: ["dual_process"], type: "recall", difficulty: 1, prompt: "Como o app pede que metáforas e modelos sejam tratados?", correctAnswer: "open", modelAnswer: "Como apoios opcionais que não substituem o mecanismo, não introduzem relações falsas, e devem ser abandonados quando geram confusão.", explanation: "Seção de metáforas do manuscrito.", hint1: "Não substituem.", hint2: "Abandonar se confundem.", hint3: "Modelo ≠ realidade." }),
      q({ id: "m21-q4", moduleId: "module_21", conceptIds: ["dual_process"], type: "application", difficulty: 2, prompt: "Um gestor diz: 'seu cérebro reptiliano atacou na reunião'. Sua correção:", options: [{ id: "a", text: "Há um processo mais automático em jogo, possivelmente defensivo; isso não é um réptil interno nem um diagnóstico." }, { id: "b", text: "Concordo: é preciso treinar o neo-córtex para dominar o lagarto." }], correctAnswer: "a", explanation: "Traduzir sem ontologizar.", hint1: "Traduza.", hint2: "Sem réptil.", hint3: "Sem diagnóstico.", errorKind: "language" }),
      q({ id: "m21-q5", moduleId: "module_21", conceptIds: ["dual_process"], type: "counterfactual", difficulty: 2, prompt: "Se você tratasse rápido/lento como anatomia literal, o que a evidência de dupla dissociação lhe faria?", options: [{ id: "a", text: "Nada: o modelo é imune a dado." }, { id: "b", text: "Falsificaria a ontologização — tarefas 'rápidas' recrutam áreas 'lentas' e vice-versa; o mapa é funcional, não parcelário." }], correctAnswer: "b", explanation: "Modelo aberto à falsificação.", hint1: "Dupla dissociação.", hint2: "Funcional.", hint3: "Não parcelário.", errorKind: "generalization" }),
    ],
    summary: { shouldKnow: ["Usar rápido/lento como modelo.", "Enterrar o triuno."], acquiredConcepts: ["dual_process"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_22",
    stage: 3,
    number: 22,
    title: "Hábitos",
    shortTitle: "Hábitos",
    objective: "Definir hábito como controle relativamente insensível à meta atual, adquirido por repetição — sem moral nem 'vício de dopamina'.",
    centralQuestion: "Por que a mão faz o caminho antigo quando a meta já mudou?",
    prerequisites: ["module_20", "module_19"],
    estimatedTime: { essential: 8, deepen: 5, questions: 4 },
    concepts: ["habit"],
    introduction: "Hábito não é preguiça. É uma solução para regularidade. Vira problema quando o ambiente muda e a política de ação não.",
    blocks: [
      { id: "m22-q", kind: "question", body: "Se eu 'não queria', por que fiz?" },
      { id: "m22-a", kind: "answer", body: "Porque um [[habit|hábito]] é relativamente insensível à meta declarada agora. Pistas de contexto disparam uma política aprendida em circuitos cortico-estriatais, em linhas gerais." },
      { id: "m22-e", kind: "explain", title: "Implicação prática", body: "Mudar pistas e rotinas costuma ser mais coerente com o mecanismo do que invocar uma substância chamada força de vontade. Isso não é conselho clínico; é coerência conceitual." },
      { id: "m22-r", kind: "recall", body: "Complete: hábito é insensível à ____ atual e sensível a ____ de contexto." },
    ],
    misconceptions: [{ claim: "Hábito é falha de caráter ou 'vício de dopamina'.", whyPlausible: "A cultura moraliza repetição.", problem: "Apaga o mecanismo e personifica a molécula.", better: "Política de ação aprendida; a dopamina entra como modulador de aprendizagem, não como essência do vício cotidiano." }],
    integration: "Vieses vão generalizar o tema: padrões sistemáticos, não estupidez.",
    relatedModules: ["module_14", "module_20", "module_30"],
    questions: [
      q({ id: "m22-q1", moduleId: "module_22", conceptIds: ["habit"], type: "recognition", difficulty: 1, prompt: "Hábito, neste curso:", options: [{ id: "a", text: "É preguiça." }, { id: "b", text: "É controle de ação relativamente insensível à meta atual, ligado a pistas estáveis." }], correctAnswer: "b", explanation: "Definição operacional.", hint1: "Meta atual.", hint2: "Pistas.", hint3: "Não moral." }),
      q({ id: "m22-q2", moduleId: "module_22", conceptIds: ["habit"], type: "application", difficulty: 2, prompt: "Alguém abre o app à noite 'sem querer'. Intervenção conceitualmente alinhada:", options: [{ id: "a", text: "Apenas se envergonhar mais." }, { id: "b", text: "Alterar pistas e a rotina de contexto; tratar como política aprendida, não como laudo." }], correctAnswer: "b", explanation: "Prévia da etapa 4, ainda sem prescrever terapia.", hint1: "Pistas.", hint2: "Contexto.", hint3: "Não laude.", errorKind: "causal" }),
      q({ id: "m22-q3", moduleId: "module_22", conceptIds: ["habit"], type: "counterfactual", difficulty: 2, prompt: "Se o contexto de pistas mudasse completamente, o hábito:", options: [{ id: "a", text: "Permaneceria idêntico, porque hábito é essência da pessoa." }, { id: "b", text: "Tenderia a se expressar menos naquele formato — a política é gatilhada por pistas." }], correctAnswer: "b", explanation: "Sensibilidade a contexto.", hint1: "Gatilho.", hint2: "Não essência.", hint3: "Pistas.", errorKind: "causal" }),
      q({ id: "m22-q4", moduleId: "module_22", conceptIds: ["dopamine"], type: "misconception", difficulty: 2, prompt: "Chamar todo hábito de 'loop de dopamina' é um problema porque:", options: [{ id: "a", text: "A dopamina não existe." }, { id: "b", text: "Reduz um fenômeno de controle de ação a uma molécula-personagem e apaga pista, meta e circuito." }], correctAnswer: "b", explanation: "Regra anti-personagem + hábito.", hint1: "Personagem.", hint2: "Circuito.", hint3: "Pista.", errorKind: "language" }),
      q({ id: "m22-q5", moduleId: "module_22", conceptIds: ["habit"], type: "recall", difficulty: 1, prompt: "Formule, com suas palavras, a diferença entre uma ação orientada por meta e um hábito.", correctAnswer: "open", modelAnswer: "A ação orientada por meta é sensível ao valor atual do resultado; o hábito é relativamente insensível a essa reavaliação e disparado por pistas de contexto, mesmo quando a meta mudou.", explanation: "Definição operacional em contraste.", hint1: "Valor atual do resultado.", hint2: "Pistas.", hint3: "Sensibilidade." }),
    ],
    summary: { shouldKnow: ["Definir hábito sem moral.", "Ligar a pistas e insensibilidade à meta."], acquiredConcepts: ["habit"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_23",
    stage: 3,
    number: 23,
    title: "Vieses cognitivos",
    shortTitle: "Vieses",
    objective: "Tratar vieses como desvios sistemáticos de um modelo normativo — heurísticas, não coleção de insultos.",
    centralQuestion: "Nomear um viés explica o mecanismo?",
    prerequisites: ["module_21"],
    estimatedTime: { essential: 7, deepen: 5, questions: 4 },
    concepts: ["cognitive_bias"],
    introduction: "Listas de vieses viralizam. O curso pede o contrário: o padrão, o contexto em que a heurística ajuda, e o que o nome não explica.",
    blocks: [
      { id: "m23-q", kind: "question", body: "Se eu disser 'isso é viés de confirmação', expliquei o caso?" },
      { id: "m23-a", kind: "answer", body: "Quase nunca. [[cognitive_bias|Viés]] é um desvio sistemático. O nome é um rótulo. Ainda faltam processo, incentivo e dados." },
      { id: "m23-e", kind: "explain", title: "Heurística útil noutro lugar", body: "Muitos vieses são o verso de atalhos que funcionam sob tempo e informação limitada. Tratar o atalho como estupidez é outro erro." },
      { id: "m23-r", kind: "recall", body: "Dê um exemplo em que um atalho acerta no cotidiano e falha num teste de laboratório." },
    ],
    misconceptions: [{ claim: "Colecionar nomes de vieses é compreender julgamento.", whyPlausible: "A lista parece expertise.", problem: "Rótulo sem mecanismo.", better: "Pergunte qual processo produziu o padrão." }],
    integration: "Predição, no módulo seguinte, oferece um princípio que atravessa percepção, ação e aprendizagem — ainda como modelo.",
    relatedModules: ["module_21", "module_24"],
    questions: [
      q({ id: "m23-q1", moduleId: "module_23", conceptIds: ["cognitive_bias"], type: "misconception", difficulty: 1, prompt: "Um viés cognitivo é:", options: [{ id: "a", text: "Prova de que a pessoa é pouco inteligente." }, { id: "b", text: "Um desvio sistemático em relação a um modelo normativo, muitas vezes ligado a heurísticas." }], correctAnswer: "b", explanation: "Sistemático ≠ estúpido.", hint1: "Sistemático.", hint2: "Normativo.", hint3: "Não QI.", errorKind: "generalization" }),
      q({ id: "m23-q2", moduleId: "module_23", conceptIds: ["cognitive_bias"], type: "limit", difficulty: 2, prompt: "Nomear o viés basta como análise de um caso?", options: [{ id: "a", text: "Sim." }, { id: "b", text: "Não. Faltam processo, evidência e, muitas vezes, mais de uma explicação possível." }], correctAnswer: "b", explanation: "Rótulo ≠ mecanismo.", hint1: "Mecanismo.", hint2: "Alternativas.", hint3: "Não basta.", errorKind: "language" }),
      q({ id: "m23-q3", moduleId: "module_23", conceptIds: ["cognitive_bias"], type: "application", difficulty: 2, prompt: "Alguém só lê o que confirma a tese. Além do rótulo, o que perguntar?", options: [{ id: "a", text: "Quais pistas, incentivos e custos de buscar o contrário estão no ambiente?" }, { id: "b", text: "Nada: o nome encerra o caso." }], correctAnswer: "a", explanation: "Ambiente e processo.", hint1: "Incentivo.", hint2: "Custo.", hint3: "Ambiente.", errorKind: "causal" }),
      q({ id: "m23-q4", moduleId: "module_23", conceptIds: ["cognitive_bias"], type: "recall", difficulty: 1, prompt: "Por que nem todo erro é um viés nomeado?", correctAnswer: "open", modelAnswer: "Porque há ruído, falta de informação, fadiga e erros não sistemáticos. Viés implica padrão. Forçar um nome é falsa precisão.", explanation: "Falsos positivos de rótulo.", hint1: "Sistemático.", hint2: "Ruído.", hint3: "Falsa precisão." }),
      q({ id: "m23-q5", moduleId: "module_23", conceptIds: ["cognitive_bias", "dual_process"], type: "relation", difficulty: 2, prompt: "Como o modelo rápido/lento se articula com o estudo de vieses, sem virar veredito?", options: [{ id: "a", text: "Todo viés prova o cérebro reptiliano falhando." }, { id: "b", text: "Heurísticas rápidas produzem padrões úteis em muitos contextos e desvios em outros; o modelo descreve o custo, não uma inferioridade." }], correctAnswer: "b", explanation: "Articulação sem hierarquia moral.", hint1: "Trade-off.", hint2: "Contexto.", hint3: "Sem hierarquia." }),
    ],
    summary: { shouldKnow: ["Definir viés sem insulto.", "Não parar no nome."], acquiredConcepts: ["cognitive_bias"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_24",
    stage: 3,
    number: 24,
    title: "Integração cognitiva",
    shortTitle: "Integração 3",
    objective: "Fechar a etapa 3 com informação → atenção → memória → avaliação → decisão → ação → aprendizagem, admitindo simultaneidade.",
    centralQuestion: "Como esses processos ocorrem juntos sem virar uma fila de montagem?",
    prerequisites: ["module_17", "module_18", "module_20", "module_22"],
    estimatedTime: { essential: 7, deepen: 4, questions: 4 },
    concepts: ["prediction", "attention", "decision_making"],
    introduction: "Não ensinar conceito novo obrigatório, salvo um princípio organizador: predição. E marcar que é modelo sustentado, não dogma.",
    blocks: [
      { id: "m24-q", kind: "question", body: "A mente é uma esteira: primeiro atenta, depois memoriza, depois decide?" },
      { id: "m24-a", kind: "answer", body: "Não. A cadeia didática ajuda a estudar. Na operação real, processos se sobrepõem. [[prediction|Predição]] atravessa vários deles: o sistema antecipa, e o erro atualiza." },
      { id: "m24-m", kind: "mechanism", title: "Cadeia de estudo, não de relógio", steps: [
        { id: "i", title: "Informação", body: "Entradas e contexto." },
        { id: "a", title: "Atenção", body: "Seleção." },
        { id: "m", title: "Memória", body: "Manutenção e traços." },
        { id: "v", title: "Avaliação", body: "Valor e relevância." },
        { id: "d", title: "Decisão e ação", body: "Políticas em competição, inclusive hábito." },
        { id: "l", title: "Aprendizagem", body: "Atualização — o fim que já estava no começo." },
      ]},
      { id: "m24-r", kind: "recall", body: "Onde o hábito fura a esteira deliberativa?" },
    ],
    misconceptions: [{ claim: "Cognição substitui biologia.", whyPlausible: "Falamos em processos mentais.", problem: "Outro nível, mesmo organismo.", better: "Descrição cognitiva sobre fundamento biológico." }],
    integration: "A etapa 4 aplica o raciocínio a pessoas reais, com o freio ético puxado.",
    relatedModules: ["module_16", "module_32"],
    questions: [
      q({ id: "m24-q1", moduleId: "module_24", conceptIds: ["prediction"], type: "integration", difficulty: 2, prompt: "A cadeia cognitiva do curso é:", options: [{ id: "a", text: "Uma esteira literal no encéfalo." }, { id: "b", text: "Um mapa de estudo; processos podem ocorrer simultaneamente, com predição atravessando níveis." }], correctAnswer: "b", explanation: "Didática versus ontologia.", hint1: "Mapa de estudo.", hint2: "Simultâneo.", hint3: "Predição." }),
      q({ id: "m24-q2", moduleId: "module_24", conceptIds: ["habit"], type: "application", difficulty: 2, prompt: "A ação dispara antes da deliberação terminar. Isso invalida a cadeia?", options: [{ id: "a", text: "Sim, o curso inteiro cai." }, { id: "b", text: "Não: mostra que controladores distintos têm temporalidades distintas — a cadeia não é um relógio único." }], correctAnswer: "b", explanation: "Hábito como furo produtivo.", hint1: "Temporalidades.", hint2: "Hábito.", hint3: "Não relógio." }),
      q({ id: "m24-q3", moduleId: "module_24", conceptIds: ["prediction"], type: "limit", difficulty: 2, prompt: "Devemos reduzir toda a mente a um algoritmo preditivo?", options: [{ id: "a", text: "Sim, é dogma." }, { id: "b", text: "Não. É um princípio organizador útil; transformá-lo em religião é o mesmo erro de qualquer slogan." }], correctAnswer: "b", explanation: "Modelo sustentado, não dogma.", hint1: "Princípio, não religião.", hint2: "Cuidado com slogans.", hint3: "Não reduza.", errorKind: "generalization" }),
      q({ id: "m24-q4", moduleId: "module_24", conceptIds: ["levels_of_analysis"], type: "recall", difficulty: 2, prompt: "Como a etapa 3 se relaciona com a 1 e a 2 sem substituí-las?", correctAnswer: "open", modelAnswer: "Como outro nível de descrição: atenção e decisão acontecem em organismos com membranas, circuitos e eixos. A cognição nomeia operações; não apaga o chão.", explanation: "Três andares, um prédio.", hint1: "Nível.", hint2: "Não substitui.", hint3: "Mesmo organismo." }),
      q({ id: "m24-q5", moduleId: "module_24", conceptIds: ["prediction", "attention"], type: "counterfactual", difficulty: 2, prompt: "Se a predição fosse retirada da descrição, o que ficaria mal explicado?", options: [{ id: "a", text: "Nada: predição é enfeite." }, { id: "b", text: "Casos em que percepção, atenção e aprendizagem se ajustam antes do estímulo — e a razão de o erro atualizar o sistema." }], correctAnswer: "b", explanation: "Princípio organizador, útil enquanto modelo.", hint1: "Antecipação.", hint2: "Erro atualiza.", hint3: "Perde o fio.", errorKind: "causal" }),
    ],
    summary: { shouldKnow: ["Recitar a cadeia cognitiva.", "Admitir simultaneidade.", "Usar predição com modestia."], acquiredConcepts: ["prediction"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
];
