import type { ModuleContent, Question } from "../types.ts";

const mastery = { comprehension: 70, recall: 70, contrast: 70, application: 60 };
const refs = [
  { title: "Rock, SCARF (NeuroLeadership Journal) — ferramenta, não anatomia", kind: "artigo" as const },
  { title: "Porges / literatura de ameaça social — ler com cautela de divulgação", kind: "revisao" as const },
  { title: "Código de ética profissional da sua área (quando houver)", kind: "instituicao" as const },
];
function q(p: Question): Question {
  return p;
}

export const STAGE_4_MODULES: ModuleContent[] = [
  {
    id: "module_25",
    stage: 4,
    number: 25,
    title: "Escuta antes da intervenção",
    shortTitle: "Escuta",
    objective: "Colocar a escuta como primeiro ato: fenômeno, contexto e interpretação da outra pessoa antes do modelo.",
    centralQuestion: "O que está acontecendo, na visão desta pessoa?",
    prerequisites: ["module_24"],
    estimatedTime: { essential: 7, deepen: 5, questions: 4 },
    concepts: ["listening"],
    introduction:
      "A etapa 4 aplica o raciocínio a situações humanas. O primeiro erro é chegar com o rótulo neural. Escutar não é técnica de venda; é recusar o encaixe precoce.",
    blocks: [
      { id: "m25-q", kind: "question", body: "Por que um modelo bom pode estragar uma conversa?" },
      { id: "m25-a", kind: "answer", body: "Porque [[listening|escutar]] colhe o fenômeno e o significado alheio. Sem isso, o modelo vira um molde. A trilha ensina mecanismos gerais, não a biografia de ninguém." },
      { id: "m25-e", kind: "explain", title: "Ordem", body: "Observável → relato → hipótese → só então teste pequeno. Inverter a ordem é o atalho que a etapa 1 já condenou entre níveis." },
      { id: "m25-r", kind: "recall", body: "Qual pergunta abre qualquer caso neste curso?" },
      { id: "m25-c", kind: "case", title: "Caso breve", body: "Alguém atrasa entregas. Você pensa 'hábito' ou 'ameaça'. Antes: o que a pessoa descreve? O contexto mudou? Há mais de uma explicação plausível?" },
    ],
    misconceptions: [{ claim: "Se eu sei neurociência, já sei o que a pessoa precisa.", whyPlausible: "O conhecimento dá confiança.", problem: "Confiança + modelo ≠ evidência sobre aquele indivíduo.", better: "Mecanismos gerais informam perguntas, não laudos." }],
    integration: "Ameaça e segurança social vão explicar por que alguém se fecha — ainda sem diagnóstico.",
    relatedModules: ["module_26", "module_28", "module_31"],
    questions: [
      q({ id: "m25-q1", moduleId: "module_25", conceptIds: ["listening"], type: "recognition", difficulty: 1, prompt: "O primeiro ato responsável é:", options: [{ id: "a", text: "Aplicar o rótulo neural." }, { id: "b", text: "Escutar fenômeno, contexto e interpretação da pessoa." }], correctAnswer: "b", explanation: "Ordem ética e epistêmica.", hint1: "Antes do modelo.", hint2: "Relato.", hint3: "Escuta." }),
      q({ id: "m25-q2", moduleId: "module_25", conceptIds: ["listening"], type: "misconception", difficulty: 2, prompt: "Usar a trilha para explicar a vida inteira de alguém é um erro porque:", options: [{ id: "a", text: "A trilha é falsa." }, { id: "b", text: "Generaliza um mecanismo e ultrapassa o que a evidência daquele caso permite." }], correctAnswer: "b", explanation: "Limite de aplicação, já no primeiro módulo da etapa.", hint1: "Aquele caso.", hint2: "Evidência.", hint3: "Não a vida inteira.", errorKind: "generalization" }),
      q({ id: "m25-q3", moduleId: "module_25", conceptIds: ["listening"], type: "application", difficulty: 2, prompt: "Na reunião que desandou, o passo 1 é:", options: [{ id: "a", text: "Diagnosticar ansiedade social." }, { id: "b", text: "Descrever o observável e ouvir como cada um interpretou, antes de hipotetizar mecanismos." }], correctAnswer: "b", explanation: "Caso do projeto final, em miniatura.", hint1: "Observável.", hint2: "Interpretação.", hint3: "Depois hipótese.", errorKind: "scale" }),
      q({ id: "m25-q4", moduleId: "module_25", conceptIds: ["listening"], type: "recall", difficulty: 1, prompt: "Como a escuta se relaciona com 'evidência versus hipótese'?", correctAnswer: "open", modelAnswer: "O relato e o observável são o que se tem; o mecanismo é hipótese até haver mais. Escutar impede que a hipótese se vista de fato.", explanation: "Transferência do módulo 1.", hint1: "Fato versus hipótese.", hint2: "Relato é dado.", hint3: "Mecanismo é proposta." }),
      q({ id: "m25-q5", moduleId: "module_25", conceptIds: ["listening"], type: "limit", difficulty: 2, prompt: "Escutar mais tempo autoriza diagnóstico neste app?", options: [{ id: "a", text: "Sim, tempo de escuta compensa formação clínica." }, { id: "b", text: "Não. Escuta prolongada melhora o fenômeno recolhido; não converte o app em contexto clínico." }], correctAnswer: "b", explanation: "Limite do papel + do produto.", hint1: "Papel.", hint2: "Contexto.", hint3: "Não converte.", errorKind: "generalization" }),
    ],
    summary: { shouldKnow: ["Abrir com o fenômeno.", "Não encaixar a pessoa no módulo favorito."], acquiredConcepts: ["listening"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_26",
    stage: 4,
    number: 26,
    title: "Ameaça, segurança e interação social",
    shortTitle: "Ameaça e segurança",
    objective: "Ligar avaliação de risco social a fisiologia e abertura, sem ler desconforto como 'amígdala disparada'.",
    centralQuestion: "O que uma crítica pública pode estar sinalizando — além do conteúdo literal?",
    prerequisites: ["module_25", "module_13"],
    estimatedTime: { essential: 8, deepen: 5, questions: 4 },
    concepts: ["threat_safety"],
    introduction: "Status, exclusão e imprevisibilidade podem recrutar defesas que você já estudou. O conteúdo agora é relacional. O erro é o atalho anatômico.",
    blocks: [
      { id: "m26-q", kind: "question", body: "Calar-se após uma crítica pública é prova de um transtorno?" },
      { id: "m26-a", kind: "answer", body: "Não. [[threat_safety|Ameaça e segurança]] sociais alteram atenção, fisiologia e fala. Há muitas explicações. Sem história e contexto, o laudo é excesso." },
      { id: "m26-e", kind: "explain", title: "O que se pode dizer", body: "Pode-se dizer: esta situação é compatível com sinal de ameaça de status. Não se pode dizer: a amígdala dele disparou e por isso tem o transtorno Y." },
      { id: "m26-r", kind: "recall", body: "Traduza um desconforto social em níveis (social, cognitivo, sistêmico) sem fechar causa única." },
    ],
    misconceptions: [{ claim: "Desconforto social = amígdala disparada = transtorno.", whyPlausible: "A cadeia parece científica.", problem: "Três saltos: de situação a estrutura, de estrutura a diagnóstico.", better: "Compatível com avaliação de ameaça; hipóteses em aberto." }],
    integration: "SCARF vai oferecer uma heurística prática para desenhar a conversa — marcada como ferramenta.",
    relatedModules: ["module_11", "module_13", "module_27"],
    questions: [
      q({ id: "m26-q1", moduleId: "module_26", conceptIds: ["threat_safety"], type: "misconception", difficulty: 1, prompt: "A melhor leitura de um silêncio após crítica pública:", options: [{ id: "a", text: "Transtorno de ansiedade, amígdala disparada." }, { id: "b", text: "Possível sinal de ameaça de status; várias explicações; sem base para diagnóstico." }], correctAnswer: "b", explanation: "Regra contra diagnóstico leigo.", hint1: "Possível.", hint2: "Várias.", hint3: "Sem laudo.", errorKind: "causal" }),
      q({ id: "m26-q2", moduleId: "module_26", conceptIds: ["threat_safety"], type: "application", difficulty: 2, prompt: "O que poderia ser testado, eticamente, nesse cenário de reunião?", options: [{ id: "a", text: "Mudar o contexto do feedback (privado, específico) e observar." }, { id: "b", text: "Anunciar o diagnóstico no grupo." }], correctAnswer: "a", explanation: "Intervenção pequena e reversível.", hint1: "Contexto.", hint2: "Observar.", hint3: "Não diagnostique.", errorKind: "generalization" }),
      q({ id: "m26-q3", moduleId: "module_26", conceptIds: ["amygdala"], type: "limit", difficulty: 2, prompt: "Por que 'sua amígdala disparou' é má comunicação e má ciência aqui?", options: [{ id: "a", text: "Porque localiza, personifica e não é observável na conversa." }, { id: "b", text: "Porque a amígdala não participa de nada social." }], correctAnswer: "a", explanation: "Mesmo que circuitos de relevância participem em geral, a frase na reunião é um salto.", hint1: "Não observável.", hint2: "Localiza.", hint3: "Personifica.", errorKind: "scale" }),
      q({ id: "m26-q4", moduleId: "module_26", conceptIds: ["threat_safety"], type: "recall", difficulty: 1, prompt: "Que eixos da etapa 2 podem participar de uma defesa social, sem serem a explicação completa?", correctAnswer: "open", modelAnswer: "Avaliação de relevância, ajustes autonômicos e, conforme duração, HPA — sempre atravessados por significado cultural e história. Nenhum deles esgota o episódio.", explanation: "Integração 2+4.", hint1: "Autonômico.", hint2: "HPA.", hint3: "Significado." }),
      q({ id: "m26-q5", moduleId: "module_26", conceptIds: ["threat_safety"], type: "counterfactual", difficulty: 2, prompt: "Se o mesmo feedback fosse dado em privado, com critérios claros, o silêncio previsto seria:", options: [{ id: "a", text: "Idêntico: contexto social não muda nada." }, { id: "b", text: "Provavelmente menor — sinais de ameaça de status caem quando exposição pública e ambiguidade caem, mas ainda sem base para diagnóstico." }], correctAnswer: "b", explanation: "Ambiente muda o sinal, não define a pessoa.", hint1: "Contexto.", hint2: "Exposição.", hint3: "Não é diagnóstico.", errorKind: "causal" }),
    ],
    summary: { shouldKnow: ["Ler ameaça social sem anatomizar a pessoa.", "Manter hipóteses múltiplas."], acquiredConcepts: ["threat_safety"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_27",
    stage: 4,
    number: 27,
    title: "Modelo SCARF",
    shortTitle: "SCARF",
    objective: "Ensinar SCARF como ferramenta de comunicação, não como mapa literal do cérebro.",
    centralQuestion: "Como preparar uma conversa difícil sem fingir anatomia?",
    prerequisites: ["module_26"],
    estimatedTime: { essential: 9, deepen: 6, questions: 5 },
    concepts: ["scarf"],
    introduction: "SCARF agrupa Status, Certainty, Autonomy, Relatedness e Fairness. É heurística. Cada dimensão tem literatura distinta. Não ontologize.",
    blocks: [
      { id: "m27-q", kind: "question", body: "SCARF é um mapa dos cinco circuitos sociais?" },
      { id: "m27-a", kind: "answer", body: "Não. [[scarf|SCARF]] é uma ferramenta prática. Útil para desenhar interações; perigosa se virar frenologia de reunião." },
      { id: "m27-d", kind: "diagram", diagram: "scarf", title: "Cinco dimensões", body: "Para cada uma: conceito → situação → possível percepção → efeito → estratégia → limite do modelo." },
      { id: "m27-m", kind: "mechanism", title: "As cinco, em modo ferramenta", steps: [
        { id: "s", title: "Status", body: "Posição relativa. Crítica pública ameaça; reconhecimento específico pode reduzir a ameaça — sem manipular." },
        { id: "c", title: "Certainty", body: "Previsibilidade. Ambiguidade crônica custa. Clareza de processo ajuda." },
        { id: "a", title: "Autonomy", body: "Sensação de controle sobre o próprio ato. Microescolhas versus microgestão." },
        { id: "r", title: "Relatedness", body: "Pertencer versus exclusão." },
        { id: "f", title: "Fairness", body: "Justiça percebida. Regras opacas queimam confiança." },
      ]},
      { id: "m27-l", kind: "limit", title: "Limite do modelo", body: "SCARF não mede o cérebro de ninguém. Não substitui direito trabalhista, cuidado clínico ou escuta. Evidence level: hipótese / ferramenta.", layer: 1 },
      { id: "m27-r", kind: "recall", body: "Escolha uma dimensão e complete: situação → percepção possível → o que você não pode concluir." },
    ],
    misconceptions: [{ claim: "SCARF descreve os cinco circuitos sociais oficiais.", whyPlausible: "A sigla é limpa e 'neural'.", problem: "Ferramenta ontologizada.", better: "Checklist de desenho de conversa, com limites explícitos." }],
    integration: "Perguntas estratégicas operacionalizam a escuta dentro (ou fora) dessas dimensões.",
    relatedModules: ["module_25", "module_28", "module_31"],
    questions: [
      q({ id: "m27-q1", moduleId: "module_27", conceptIds: ["scarf"], type: "misconception", difficulty: 1, prompt: "SCARF é:", options: [{ id: "a", text: "Um mapa literal do cérebro social." }, { id: "b", text: "Uma heurística de comunicação (status, certeza, autonomia, vínculo, justiça)." }], correctAnswer: "b", explanation: "Ferramenta, não anatomia.", hint1: "Heurística.", hint2: "Cinco palavras.", hint3: "Não mapa.", errorKind: "language" }),
      q({ id: "m27-q2", moduleId: "module_27", conceptIds: ["scarf"], type: "application", difficulty: 2, prompt: "Feedback difícil alinhado ao modelo (sem manipulação):", options: [{ id: "a", text: "Público, vago, sem direito a resposta." }, { id: "b", text: "Privado, específico, com clareza de critérios e espaço de resposta." }], correctAnswer: "b", explanation: "Status + fairness + autonomy, como desenho, não como circuito.", hint1: "Privado.", hint2: "Específico.", hint3: "Critérios." }),
      q({ id: "m27-q3", moduleId: "module_27", conceptIds: ["scarf"], type: "limit", difficulty: 2, prompt: "Se a pessoa não reagir como o SCARF 'prevê':", options: [{ id: "a", text: "O cérebro dela está errado." }, { id: "b", text: "O modelo é incompleto; volte à escuta. Não force o encaixe." }], correctAnswer: "b", explanation: "Ferramentas falham. A pessoa não.", hint1: "Incompleto.", hint2: "Escuta.", hint3: "Não force.", errorKind: "generalization" }),
      q({ id: "m27-q4", moduleId: "module_27", conceptIds: ["scarf"], type: "recall", difficulty: 1, prompt: "Liste as cinco dimensões e diga, para uma delas, um limite.", correctAnswer: "open", modelAnswer: "Status, Certainty, Autonomy, Relatedness, Fairness. Ex.: Status — reconhecimento não substitui justiça estrutural; não use a dimensão para lisonjear e calar crítica legítima.", explanation: "Conceito + limite, como o manuscrito pede.", hint1: "A sigla.", hint2: "Um limite ético.", hint3: "Não manipule." }),
      q({ id: "m27-q5", moduleId: "module_27", conceptIds: ["evidence_vs_hypothesis"], type: "relation", difficulty: 2, prompt: "O nível de evidência do SCARF neste app é tratado como:", options: [{ id: "a", text: "Bem estabelecido como anatomia." }, { id: "b", text: "Ferramenta / hipótese prática, separada do que é bem estabelecido em fisiologia." }], correctAnswer: "b", explanation: "Camada de confiança científica.", hint1: "Ferramenta.", hint2: "Não anatomia.", hint3: "Separe." }),
    ],
    summary: { shouldKnow: ["Recitar SCARF.", "Usar como checklist.", "Declarar o limite."], acquiredConcepts: ["scarf"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_28",
    stage: 4,
    number: 28,
    title: "Perguntas estratégicas",
    shortTitle: "Perguntas",
    objective: "Formar perguntas que revelam mecanismo e contexto, em vez de perguntas que já contêm o diagnóstico.",
    centralQuestion: "Que pergunta abre o mecanismo sem fechar a pessoa?",
    prerequisites: ["module_25"],
    estimatedTime: { essential: 7, deepen: 5, questions: 4 },
    concepts: ["strategic_questions"],
    introduction: "A trilha inteira é uma pedagogia da pergunta. Agora ela vira ofício: perguntar para ver, não para confirmar o módulo favorito.",
    blocks: [
      { id: "m28-q", kind: "question", body: "'Você está ansioso?' é uma boa primeira pergunta?" },
      { id: "m28-a", kind: "answer", body: "Em geral, não. Já entrega o rótulo. [[strategic_questions|Perguntas estratégicas]] pedem sequência, contexto, exceção e o que se pode concluir." },
      { id: "m28-m", kind: "mechanism", title: "Família útil", steps: [
        { id: "o", title: "Observável", body: "O que acontece, concretamente?" },
        { id: "t", title: "Tempo", body: "O que vem imediatamente antes e depois?" },
        { id: "x", title: "Exceção", body: "Quando isso não acontece?" },
        { id: "h", title: "Hipótese", body: "O que isso permite — e o que não permite — concluir?" },
      ]},
      { id: "m28-r", kind: "recall", body: "Transforme 'você tem TDAH?' em duas perguntas que não diagnostiquem." },
    ],
    misconceptions: [{ claim: "Perguntas boas já contêm a resposta certa.", whyPlausible: "Eficiência.", problem: "Viés de confirmação com jaleco.", better: "Perguntas que poderiam falsificar a hipótese favorita." }],
    integration: "Regulação entra quando a conversa precisa de timing, não só de conteúdo.",
    relatedModules: ["module_23", "module_25", "module_29"],
    questions: [
      q({ id: "m28-q1", moduleId: "module_28", conceptIds: ["strategic_questions"], type: "recognition", difficulty: 1, prompt: "Uma pergunta estratégica:", options: [{ id: "a", text: "Já inclui o diagnóstico." }, { id: "b", text: "Revela sequência, contexto ou limite do que se pode concluir." }], correctAnswer: "b", explanation: "Abrir, não fechar.", hint1: "Sequência.", hint2: "Limite.", hint3: "Não rótulo." }),
      q({ id: "m28-q2", moduleId: "module_28", conceptIds: ["strategic_questions"], type: "application", difficulty: 2, prompt: "Melhor par de perguntas para o estudo que 'não gruda':", options: [{ id: "a", text: "'Você é preguiçoso?' / 'Tem déficit de dopamina?'" }, { id: "b", text: "'O que você faz quando estuda?' / 'Consegue reconstruir o mecanismo sem olhar?'" }], correctAnswer: "b", explanation: "Processo observável versus essência.", hint1: "Comportamento de estudo.", hint2: "Reconstrução.", hint3: "Não essência.", errorKind: "language" }),
      q({ id: "m28-q3", moduleId: "module_28", conceptIds: ["strategic_questions"], type: "recall", difficulty: 1, prompt: "Por que perguntar pela exceção é poderoso?", correctAnswer: "open", modelAnswer: "Porque uma hipótese que não sobrevive à exceção era generalização. A exceção revela contexto e falsifica o 'sempre'.", explanation: "Anti-generalização.", hint1: "Sempre.", hint2: "Falsificar.", hint3: "Contexto." }),
      q({ id: "m28-q4", moduleId: "module_28", conceptIds: ["cognitive_bias"], type: "limit", difficulty: 2, prompt: "Se todas as suas perguntas só podem confirmar o módulo 22 (hábito):", options: [{ id: "a", text: "Você está sendo eficiente." }, { id: "b", text: "Você está enviesado: falte uma pergunta que poderia mostrar outra explicação." }], correctAnswer: "b", explanation: "O viés agora é do analista.", hint1: "Confirmação.", hint2: "Outra explicação.", hint3: "Falte a pergunta.", errorKind: "generalization" }),
      q({ id: "m28-q5", moduleId: "module_28", conceptIds: ["strategic_questions"], type: "misconception", difficulty: 2, prompt: "Uma pergunta 'aberta' é sempre estratégica?", options: [{ id: "a", text: "Sim, aberta e estratégica são sinônimos." }, { id: "b", text: "Não. Uma pergunta aberta ainda pode conduzir para o diagnóstico favorito; estratégica é aquela que abre alternativas testáveis." }], correctAnswer: "b", explanation: "Abertura formal não garante isenção.", hint1: "Formato.", hint2: "Direção.", hint3: "Alternativas.", errorKind: "language" }),
    ],
    summary: { shouldKnow: ["Trocar rótulo por sequência.", "Incluir exceção e limite."], acquiredConcepts: ["strategic_questions"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_29",
    stage: 4,
    number: 29,
    title: "Comunicação e regulação",
    shortTitle: "Regulação",
    objective: "Ver a comunicação como capaz de ajudar ou piorar a regulação — timing e ameaça, não 'controle-se'.",
    centralQuestion: "Esta conversa, neste momento, regula ou desregula?",
    prerequisites: ["module_26", "module_17"],
    estimatedTime: { essential: 7, deepen: 5, questions: 4 },
    concepts: ["regulation"],
    introduction: "Regulação não é um interruptor moral. Pode ser atencional, reavaliativa, corporal, relacional (co-regulação). A conversa é parte do sistema.",
    blocks: [
      { id: "m29-q", kind: "question", body: "'Controle-se' descreve um mecanismo?" },
      { id: "m29-a", kind: "answer", body: "Não. [[regulation|Regular]] é alterar intensidade, duração ou expressão de um estado. A ordem 'controle-se' ignora carga, ameaça e timing." },
      { id: "m29-e", kind: "explain", title: "Implicação", body: "Às vezes o conteúdo certo no momento errado piora o episódio. Adiar cinco minutos pode ser a intervenção. Isso não é manipulação se for transparente e respeitoso." },
      { id: "m29-r", kind: "recall", body: "Dê um exemplo de co-regulação que não é aconselhamento clínico." },
    ],
    misconceptions: [{ claim: "Regulação é força de vontade pura.", whyPlausible: "A cultura ama o herói.", problem: "Apaga atenção, contexto e o outro.", better: "Processos múltiplos, inclusive relacionais." }],
    integration: "Agora podemos transformar conhecimento em intervenção testável — ainda sem jaleco.",
    relatedModules: ["module_17", "module_26", "module_30"],
    questions: [
      q({ id: "m29-q1", moduleId: "module_29", conceptIds: ["regulation"], type: "misconception", difficulty: 1, prompt: "Regulação é:", options: [{ id: "a", text: "Um interruptor de caráter." }, { id: "b", text: "Processos que alteram intensidade, duração ou expressão de um estado, inclusive relacionais." }], correctAnswer: "b", explanation: "Plural e relacional.", hint1: "Processos.", hint2: "Inclui o outro.", hint3: "Não interruptor.", errorKind: "language" }),
      q({ id: "m29-q2", moduleId: "module_29", conceptIds: ["regulation"], type: "application", difficulty: 2, prompt: "Alguém está visivelmente no limite. Conteúdo analítico agora:", options: [{ id: "a", text: "Pode aumentar a carga; timing é parte da regulação." }, { id: "b", text: "Sempre ajuda, porque verdade acalma automaticamente." }], correctAnswer: "a", explanation: "Timing.", hint1: "Carga.", hint2: "Agora versus depois.", hint3: "Não sempre.", errorKind: "causal" }),
      q({ id: "m29-q3", moduleId: "module_29", conceptIds: ["regulation"], type: "recall", difficulty: 1, prompt: "Como atenção entra na regulação?", correctAnswer: "open", modelAnswer: "Selecionar ou desengajar de um conteúdo muda a entrada que sustenta o estado. Não é o único caminho, e não é supressão heroica.", explanation: "Ponte módulo 17.", hint1: "Seleção.", hint2: "Entrada.", hint3: "Não o único." }),
      q({ id: "m29-q4", moduleId: "module_29", conceptIds: ["regulation"], type: "limit", difficulty: 2, prompt: "Co-regulação neste curso autoriza terapia improvisada?", options: [{ id: "a", text: "Sim, agora você é terapeuta." }, { id: "b", text: "Não. Autoriza respeito ao timing e à ameaça numa conversa cotidiana, dentro do seu papel." }], correctAnswer: "b", explanation: "Papel e limite.", hint1: "Papel.", hint2: "Cotidiano.", hint3: "Não terapeuta.", errorKind: "generalization" }),
      q({ id: "m29-q5", moduleId: "module_29", conceptIds: ["regulation"], type: "counterfactual", difficulty: 2, prompt: "Se a conversa acontecesse cinco minutos depois, com o mesmo conteúdo, o efeito provável seria:", options: [{ id: "a", text: "Idêntico: o timing é indiferente." }, { id: "b", text: "Frequentemente diferente — carga cai, avaliação muda, e o mesmo conteúdo pode ajudar em vez de piorar." }], correctAnswer: "b", explanation: "Timing como parte do mecanismo.", hint1: "Carga.", hint2: "Avaliação.", hint3: "Mesma frase, outro efeito.", errorKind: "causal" }),
    ],
    summary: { shouldKnow: ["Definir regulação sem moral.", "Incluir timing na comunicação."], acquiredConcepts: ["regulation"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_30",
    stage: 4,
    number: 30,
    title: "Transformando conhecimento em intervenção",
    shortTitle: "Intervenção",
    objective: "Formular uma ação testável, ética e reversível — hipótese, não laudo.",
    centralQuestion: "O que poderia ser testado, e como saberíamos se ajudou?",
    prerequisites: ["module_25", "module_28"],
    estimatedTime: { essential: 8, deepen: 5, questions: 4 },
    concepts: ["intervention"],
    introduction: "Intervir é mudar uma variável e observar. Não é diagnosticar. O conhecimento de mecanismos sugere variáveis, não destinos.",
    blocks: [
      { id: "m30-q", kind: "question", body: "Se a pessoa faz X, ela tem o transtorno Y?" },
      { id: "m30-a", kind: "answer", body: "Não. Esse comportamento pode ter diversas explicações. É necessário considerar contexto, história, estado atual e, quando pertinente, avaliação profissional. [[intervention|Intervenção responsável]] é um teste, não um veredito." },
      { id: "m30-m", kind: "mechanism", title: "Receita mínima", steps: [
        { id: "v", title: "Variável", body: "Uma mudança pequena (pista, horário, formato do feedback)." },
        { id: "c", title: "Critério", body: "O que contaria como melhora observável." },
        { id: "t", title: "Tempo", body: "Quando rever." },
        { id: "r", title: "Reversibilidade e consentimento", body: "Dá para voltar atrás? A pessoa concordou?" },
      ]},
      { id: "m30-r", kind: "recall", body: "Escreva uma intervenção de uma frase que poderia falhar — se não pode falhar, não é teste." },
    ],
    misconceptions: [{ claim: "Se faz X, tem Y.", whyPlausible: "Atalho clínico de corredor.", problem: "Comportamento ≠ transtorno; falta base.", better: "Hipóteses múltiplas + encaminhamento quando couber." }],
    integration: "O próximo módulo é só sobre o que você não pode fazer.",
    relatedModules: ["module_31", "module_32", "module_22"],
    questions: [
      q({ id: "m30-q1", moduleId: "module_30", conceptIds: ["intervention"], type: "misconception", difficulty: 1, prompt: "A frase proibida do manuscrito é do tipo:", options: [{ id: "a", text: "'Se a pessoa faz X, provavelmente possui transtorno Y.'" }, { id: "b", text: "'Esse comportamento pode ter diversas explicações.'" }], correctAnswer: "a", explanation: "A opção A é exatamente o que evitar. A pergunta pede identificar a proibida.", hint1: "Diagnóstico leigo.", hint2: "Provavelmente possui.", hint3: "A primeira.", errorKind: "generalization" }),
      q({ id: "m30-q2", moduleId: "module_30", conceptIds: ["intervention"], type: "application", difficulty: 2, prompt: "Para o caminho automático do celular, uma intervenção alinhada:", options: [{ id: "a", text: "Mudar a pista (carregar fora do quarto) e combinar um critério de uma semana." }, { id: "b", text: "Diagnosticar adição e anunciar na família." }], correctAnswer: "a", explanation: "Pista + critério, sem laudo.", hint1: "Hábito.", hint2: "Pista.", hint3: "Critério." }),
      q({ id: "m30-q3", moduleId: "module_30", conceptIds: ["intervention"], type: "limit", difficulty: 2, prompt: "Se a intervenção 'funcionar', isso prova o mecanismo hipotetizado?", options: [{ id: "a", text: "Sim, causa única encontrada." }, { id: "b", text: "Não necessariamente. Outras variáveis podem ter mudado; sucesso prático ≠ prova causal completa." }], correctAnswer: "b", explanation: "Mesma disciplina da etapa 1.", hint1: "Causa.", hint2: "Outras variáveis.", hint3: "Não necessariamente.", errorKind: "causal" }),
      q({ id: "m30-q4", moduleId: "module_30", conceptIds: ["intervention"], type: "recall", difficulty: 1, prompt: "Quais quatro ingredientes mínimos de uma intervenção responsável?", correctAnswer: "open", modelAnswer: "Variável pequena, critério observável, horizonte de revisão, consentimento/reversibilidade. Sem diagnóstico.", explanation: "Receita.", hint1: "Variável.", hint2: "Critério.", hint3: "Consentimento." }),
      q({ id: "m30-q5", moduleId: "module_30", conceptIds: ["intervention"], type: "counterfactual", difficulty: 2, prompt: "Se a intervenção 'falhar' no critério previsto, o que essa falha permite concluir?", options: [{ id: "a", text: "Que o mecanismo hipotetizado está definitivamente errado." }, { id: "b", text: "Que aquela variável, naquela dose e prazo, não bastou — o mecanismo continua hipótese; convém revisar, não sentenciar." }], correctAnswer: "b", explanation: "Falha é dado, não veredito.", hint1: "Dose.", hint2: "Prazo.", hint3: "Revisar.", errorKind: "causal" }),
    ],
    summary: { shouldKnow: ["Recusar o se X então transtorno Y.", "Montar um teste pequeno."], acquiredConcepts: ["intervention"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_31",
    stage: 4,
    number: 31,
    title: "Limites da aplicação",
    shortTitle: "Limites",
    objective: "Deixar explícito o que a trilha não autoriza: diagnóstico, prescrição, certeza sobre a mente alheia.",
    centralQuestion: "O que não pode ser concluído?",
    prerequisites: ["module_30"],
    estimatedTime: { essential: 7, deepen: 4, questions: 4 },
    concepts: ["limits_of_application", "evidence_vs_hypothesis"],
    introduction: "Uma boa resposta pode ser: há evidências de X, mas não é possível concluir Y. Isso é habilidade, não fraqueza. Saúde: mecanismos não substituem avaliação clínica individual.",
    blocks: [
      { id: "m31-q", kind: "question", body: "Qual é o produto desta trilha?" },
      { id: "m31-a", kind: "answer", body: "Raciocínio neurocientífico, não licença clínica. [[limits_of_application|Limites]] são parte do domínio, não um anexo jurídico." },
      { id: "m31-m", kind: "mechanism", title: "Lista de não", steps: [
        { id: "d", title: "Não diagnosticar", body: "Nem a si, nem ao outro, a partir destes módulos." },
        { id: "p", title: "Não prescrever", body: "Fármaco, protocolo terapêutico, laudo." },
        { id: "c", title: "Não ler mentes", body: "Circuitos gerais ≠ o que esta pessoa é." },
        { id: "s", title: "Não vender milagre", body: "Plasticidade, dopamina, SCARF — nenhum é varinha." },
      ]},
      { id: "m31-h", kind: "explain", title: "Princípio sobre saúde", body: "Conhecimento sobre mecanismos neurobiológicos não substitui avaliação clínica individual." },
      { id: "m31-r", kind: "recall", body: "Escreva uma frase de incerteza que seria uma boa resposta num caso ambíguo." },
    ],
    misconceptions: [{ claim: "Ciência é sempre achar a resposta única.", whyPlausible: "A escola premia certeza.", problem: "Casos humanos são subdeterminados.", better: "Incerteza bem formada é critério de qualidade." }],
    integration: "O projeto final pede exatamente essa disciplina em sete campos.",
    relatedModules: ["module_01", "module_30", "module_32"],
    questions: [
      q({ id: "m31-q1", moduleId: "module_31", conceptIds: ["limits_of_application"], type: "limit", difficulty: 1, prompt: "Este aplicativo autoriza diagnóstico?", options: [{ id: "a", text: "Sim, ao terminar a trilha." }, { id: "b", text: "Não. Forma raciocínio; não concede licença clínica." }], correctAnswer: "b", explanation: "Linha vermelha.", hint1: "Licença.", hint2: "Raciocínio.", hint3: "Não." }),
      q({ id: "m31-q2", moduleId: "module_31", conceptIds: ["evidence_vs_hypothesis"], type: "recognition", difficulty: 1, prompt: "Uma boa resposta pode ser:", options: [{ id: "a", text: "'Há evidências de X, mas não é possível concluir Y apenas com essas informações.'" }, { id: "b", text: "'Tenho certeza absoluta porque li um módulo.'" }], correctAnswer: "a", explanation: "Incerteza como habilidade.", hint1: "Manuscrito §119.", hint2: "X versus Y.", hint3: "A primeira." }),
      q({ id: "m31-q3", moduleId: "module_31", conceptIds: ["limits_of_application"], type: "application", difficulty: 2, prompt: "Um amigo pede que você 'leia o cérebro dele' depois deste curso. Você:", options: [{ id: "a", text: "Recusa o papel, oferece perguntas e, se houver sofrimento, sugere cuidado profissional." }, { id: "b", text: "Entrega um laudo com amígdala e dopamina." }], correctAnswer: "a", explanation: "Papel.", hint1: "Recuse o jaleco.", hint2: "Perguntas.", hint3: "Cuidado profissional.", errorKind: "generalization" }),
      q({ id: "m31-q4", moduleId: "module_31", conceptIds: ["limits_of_application"], type: "recall", difficulty: 1, prompt: "Complete: conhecimento de mecanismos não substitui ____.", correctAnswer: "open", modelAnswer: "Avaliação clínica individual (nem o consentimento, nem o contexto, nem os limites da sua formação).", explanation: "Frase do manuscrito.", hint1: "Clínica.", hint2: "Individual.", hint3: "Avaliação." }),
      q({ id: "m31-q5", moduleId: "module_31", conceptIds: ["limits_of_application"], type: "misconception", difficulty: 2, prompt: "'Se terminei a trilha, ganhei licença para orientar decisões clínicas de terceiros' — o problema com essa frase é:", options: [{ id: "a", text: "Nenhum: certificado é licença." }, { id: "b", text: "Confunde conclusão de aprendizado com credencial regulada; a trilha forma raciocínio, não habilita prática clínica." }], correctAnswer: "b", explanation: "Certificado ≠ licença.", hint1: "Regulação.", hint2: "Raciocínio.", hint3: "Não é jaleco.", errorKind: "generalization" }),
    ],
    summary: { shouldKnow: ["Recusar diagnóstico e prescrição.", "Valorizar incerteza explícita."], acquiredConcepts: ["limits_of_application"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
  {
    id: "module_32",
    stage: 4,
    number: 32,
    title: "Projeto final",
    shortTitle: "Projeto final",
    objective: "Integrar a trilha numa situação complexa: sete campos e uma rubrica de 24 pontos — qualidade da resposta, não inteligência.",
    centralQuestion: "Diante de um caso ambíguo, você reconstrói, diferencia e reconhece limites?",
    prerequisites: ["module_31"],
    estimatedTime: { essential: 8, deepen: 4, questions: 3 },
    concepts: ["evidence_vs_hypothesis", "levels_of_analysis", "limits_of_application"],
    introduction:
      "Não queremos que você apenas saiba a resposta. Queremos que consiga reconstruir por que ela faz sentido e reconhecer quando deixa de fazer. Escolha um caso, preencha os sete campos, e não fuja da incerteza.",
    blocks: [
      { id: "m32-q", kind: "question", body: "Qual caso resiste a uma palavra-chave única?" },
      { id: "m32-a", kind: "answer", body: "Qualquer um dos três oferecidos. Se a sua análise cabe numa palavra ('amígdala', 'dopamina', 'hábito'), ela ainda não é o projeto." },
      { id: "m32-m", kind: "mechanism", title: "Sete campos", steps: [
        { id: "1", title: "Fenômeno", body: "O observável." },
        { id: "2", title: "Hipóteses", body: "Mais de uma." },
        { id: "3", title: "Biológico", body: "Escala declarada." },
        { id: "4", title: "Cognitivo", body: "Processos, não slogans." },
        { id: "5", title: "Contexto", body: "Social e ambiental." },
        { id: "6", title: "Intervenção", body: "Teste pequeno." },
        { id: "7", title: "Limitações", body: "O que não se conclui." },
      ]},
      { id: "m32-rub", kind: "explain", title: "Rubrica (0–4 cada, total 24)", body: "Precisão científica · Integração entre níveis · Qualidade da explicação · Distinção evidência/hipótese · Aplicação · Reconhecimento das limitações. A pontuação não representa inteligência." },
      { id: "m32-r", kind: "recall", body: "Antes de escrever: recuse três slogans que você não usará." },
    ],
    misconceptions: [{ claim: "O projeto pede a resposta certa única.", whyPlausible: "Provas escolares.", problem: "O caso é feito para impedir a palavra-chave.", better: "Qualidade do raciocínio e dos limites." }],
    integration: "Ao terminar, a trilha não acaba: conceitos voltam em revisões. Aprendizagem não é um certificado de 100%.",
    relatedModules: ["module_01", "module_16", "module_24", "module_31"],
    questions: [
      q({ id: "m32-q1", moduleId: "module_32", conceptIds: ["levels_of_analysis"], type: "integration", difficulty: 3, prompt: "Uma análise só com uma molécula, no projeto final:", options: [{ id: "a", text: "É o ouro da precisão." }, { id: "b", text: "Falha em integração entre níveis e provavelmente em limites." }], correctAnswer: "b", explanation: "Rubrica: integração.", hint1: "Níveis.", hint2: "Integração.", hint3: "Não uma molécula." }),
      q({ id: "m32-q2", moduleId: "module_32", conceptIds: ["evidence_vs_hypothesis"], type: "limit", difficulty: 2, prompt: "No campo limitações, uma boa frase:", options: [{ id: "a", text: "'Não há limitações porque terminei o curso.'" }, { id: "b", text: "'Não é possível diagnosticar nem atribuir causa única com o que foi dado.'" }], correctAnswer: "b", explanation: "Campo 7 não pode estar vazio de conteúdo.", hint1: "Diagnóstico.", hint2: "Causa única.", hint3: "O que foi dado." }),
      q({ id: "m32-q3", moduleId: "module_32", conceptIds: ["limits_of_application"], type: "application", difficulty: 3, prompt: "O critério definitivo de sucesso da trilha inclui:", options: [{ id: "a", text: "Recitar 32 títulos." }, { id: "b", text: "Reconstruir mecanismos, detectar simplificações, aplicar a situações novas e reconhecer incertezas." }], correctAnswer: "b", explanation: "§172 do manuscrito.", hint1: "Reconstruir.", hint2: "Incerteza.", hint3: "Não recitar." }),
      q({ id: "m32-q4", moduleId: "module_32", conceptIds: ["levels_of_analysis", "evidence_vs_hypothesis"], type: "recall", difficulty: 2, prompt: "Por que o campo 'Biológico' pede escala declarada?", correctAnswer: "open", modelAnswer: "Porque afirmações biológicas moram em níveis distintos (molecular, celular, circuito, sistema); sem declarar a escala, o argumento salta níveis e vira slogan.", explanation: "Retomada do módulo 1.", hint1: "Níveis.", hint2: "Salto.", hint3: "Escala." }),
      q({ id: "m32-q5", moduleId: "module_32", conceptIds: ["limits_of_application"], type: "misconception", difficulty: 2, prompt: "Preencher todos os sete campos com certeza absoluta é um bom projeto?", options: [{ id: "a", text: "Sim, quanto mais certeza, melhor." }, { id: "b", text: "Não. A rubrica pontua o reconhecimento de limites; certeza total no campo 7 é sinal de projeto ruim." }], correctAnswer: "b", explanation: "Incerteza bem formada como qualidade.", hint1: "Rubrica.", hint2: "Campo 7.", hint3: "Certeza ≠ qualidade.", errorKind: "generalization" }),
    ],
    summary: { shouldKnow: ["Preencher sete campos sem palavra-chave.", "Usar a rubrica como autoavaliação, não como QI."], acquiredConcepts: ["evidence_vs_hypothesis", "limits_of_application"] },
    masteryCriteria: mastery,
    references: refs,
    contentVersion: "1.0",
  },
];
