/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as ConceitosRouteImport } from './routes/conceitos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as DesafiosRouteImport } from './routes/desafios'
import { Route as DominioRouteImport } from './routes/dominio'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as GlossarioRouteImport } from './routes/glossario'
import { Route as MaisRouteImport } from './routes/mais'
import { Route as MitosRouteImport } from './routes/mitos'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as RevisoesRouteImport } from './routes/revisoes'
import { Route as TrilhaRouteImport } from './routes/trilha'
import { Route as ConceitoConceptIdRouteImport } from './routes/conceito.$conceptId'
import { Route as DominioTabRouteImport } from './routes/dominio.$tab'
import { Route as ModuloModuleIdRouteImport } from './routes/modulo.$moduleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceitosRoute = ConceitosRouteImport.update({
  id: '/conceitos',
  path: '/conceitos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const DesafiosRoute = DesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => rootRouteImport,
} as any)
const DominioRoute = DominioRouteImport.update({
  id: '/dominio',
  path: '/dominio',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossarioRoute = GlossarioRouteImport.update({
  id: '/glossario',
  path: '/glossario',
  getParentRoute: () => rootRouteImport,
} as any)
const MaisRoute = MaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => rootRouteImport,
} as any)
const MitosRoute = MitosRouteImport.update({
  id: '/mitos',
  path: '/mitos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisoesRoute = RevisoesRouteImport.update({
  id: '/revisoes',
  path: '/revisoes',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhaRoute = TrilhaRouteImport.update({
  id: '/trilha',
  path: '/trilha',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceitoConceptIdRoute = ConceitoConceptIdRouteImport.update({
  id: '/conceito/$conceptId',
  path: '/conceito/$conceptId',
  getParentRoute: () => rootRouteImport,
} as any)
const DominioTabRoute = DominioTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => DominioRoute,
} as any)
const ModuloModuleIdRoute = ModuloModuleIdRouteImport.update({
  id: '/modulo/$moduleId',
  path: '/modulo/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/conceitos': typeof ConceitosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/desafios': typeof DesafiosRoute
  '/dominio': typeof DominioRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/glossario': typeof GlossarioRoute
  '/mais': typeof MaisRoute
  '/mitos': typeof MitosRoute
  '/progresso': typeof ProgressoRoute
  '/revisoes': typeof RevisoesRoute
  '/trilha': typeof TrilhaRoute
  '/conceito/$conceptId': typeof ConceitoConceptIdRoute
  '/dominio/$tab': typeof DominioTabRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/conceitos': typeof ConceitosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/desafios': typeof DesafiosRoute
  '/dominio': typeof DominioRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/glossario': typeof GlossarioRoute
  '/mais': typeof MaisRoute
  '/mitos': typeof MitosRoute
  '/progresso': typeof ProgressoRoute
  '/revisoes': typeof RevisoesRoute
  '/trilha': typeof TrilhaRoute
  '/conceito/$conceptId': typeof ConceitoConceptIdRoute
  '/dominio/$tab': typeof DominioTabRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/busca': typeof BuscaRoute
  '/conceitos': typeof ConceitosRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/desafios': typeof DesafiosRoute
  '/dominio': typeof DominioRouteWithChildren
  '/favoritos': typeof FavoritosRoute
  '/glossario': typeof GlossarioRoute
  '/mais': typeof MaisRoute
  '/mitos': typeof MitosRoute
  '/progresso': typeof ProgressoRoute
  '/revisoes': typeof RevisoesRoute
  '/trilha': typeof TrilhaRoute
  '/conceito/$conceptId': typeof ConceitoConceptIdRoute
  '/dominio/$tab': typeof DominioTabRoute
  '/modulo/$moduleId': typeof ModuloModuleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/busca'
    | '/conceitos'
    | '/configuracoes'
    | '/desafios'
    | '/dominio'
    | '/favoritos'
    | '/glossario'
    | '/mais'
    | '/mitos'
    | '/progresso'
    | '/revisoes'
    | '/trilha'
    | '/conceito/$conceptId'
    | '/dominio/$tab'
    | '/modulo/$moduleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/busca'
    | '/conceitos'
    | '/configuracoes'
    | '/desafios'
    | '/dominio'
    | '/favoritos'
    | '/glossario'
    | '/mais'
    | '/mitos'
    | '/progresso'
    | '/revisoes'
    | '/trilha'
    | '/conceito/$conceptId'
    | '/dominio/$tab'
    | '/modulo/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/busca'
    | '/conceitos'
    | '/configuracoes'
    | '/desafios'
    | '/dominio'
    | '/favoritos'
    | '/glossario'
    | '/mais'
    | '/mitos'
    | '/progresso'
    | '/revisoes'
    | '/trilha'
    | '/conceito/$conceptId'
    | '/dominio/$tab'
    | '/modulo/$moduleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuscaRoute: typeof BuscaRoute
  ConceitosRoute: typeof ConceitosRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DesafiosRoute: typeof DesafiosRoute
  DominioRoute: typeof DominioRouteWithChildren
  FavoritosRoute: typeof FavoritosRoute
  GlossarioRoute: typeof GlossarioRoute
  MaisRoute: typeof MaisRoute
  MitosRoute: typeof MitosRoute
  ProgressoRoute: typeof ProgressoRoute
  RevisoesRoute: typeof RevisoesRoute
  TrilhaRoute: typeof TrilhaRoute
  ConceitoConceptIdRoute: typeof ConceitoConceptIdRoute
  ModuloModuleIdRoute: typeof ModuloModuleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conceitos': {
      id: '/conceitos'
      path: '/conceitos'
      fullPath: '/conceitos'
      preLoaderRoute: typeof ConceitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desafios': {
      id: '/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof DesafiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dominio': {
      id: '/dominio'
      path: '/dominio'
      fullPath: '/dominio'
      preLoaderRoute: typeof DominioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossario': {
      id: '/glossario'
      path: '/glossario'
      fullPath: '/glossario'
      preLoaderRoute: typeof GlossarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mais': {
      id: '/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof MaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitos': {
      id: '/mitos'
      path: '/mitos'
      fullPath: '/mitos'
      preLoaderRoute: typeof MitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisoes': {
      id: '/revisoes'
      path: '/revisoes'
      fullPath: '/revisoes'
      preLoaderRoute: typeof RevisoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilha': {
      id: '/trilha'
      path: '/trilha'
      fullPath: '/trilha'
      preLoaderRoute: typeof TrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conceito/$conceptId': {
      id: '/conceito/$conceptId'
      path: '/conceito/$conceptId'
      fullPath: '/conceito/$conceptId'
      preLoaderRoute: typeof ConceitoConceptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dominio/$tab': {
      id: '/dominio/$tab'
      path: '/$tab'
      fullPath: '/dominio/$tab'
      preLoaderRoute: typeof DominioTabRouteImport
      parentRoute: typeof DominioRoute
    }
    '/modulo/$moduleId': {
      id: '/modulo/$moduleId'
      path: '/modulo/$moduleId'
      fullPath: '/modulo/$moduleId'
      preLoaderRoute: typeof ModuloModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DominioRouteChildren {
  DominioTabRoute: typeof DominioTabRoute
}

const DominioRouteChildren: DominioRouteChildren = {
  DominioTabRoute: DominioTabRoute,
}

const DominioRouteWithChildren =
  DominioRoute._addFileChildren(DominioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuscaRoute: BuscaRoute,
  ConceitosRoute: ConceitosRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DesafiosRoute: DesafiosRoute,
  DominioRoute: DominioRouteWithChildren,
  FavoritosRoute: FavoritosRoute,
  GlossarioRoute: GlossarioRoute,
  MaisRoute: MaisRoute,
  MitosRoute: MitosRoute,
  ProgressoRoute: ProgressoRoute,
  RevisoesRoute: RevisoesRoute,
  TrilhaRoute: TrilhaRoute,
  ConceitoConceptIdRoute: ConceitoConceptIdRoute,
  ModuloModuleIdRoute: ModuloModuleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
